In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.1.4'

In [3]:
ser = pd.Series(['mango','banana','orange','chickoo'])

ser

0      mango
1     banana
2     orange
3    chickoo
dtype: object

In [4]:
type(ser)

pandas.core.series.Series

In [5]:
ser[1:]

1     banana
2     orange
3    chickoo
dtype: object

In [6]:
ser.count()

4

In [6]:
type(ser)

pandas.core.series.Series

In [7]:
fruits = ['mango','banana','orange','chickoo']

ser = pd.Series(fruits)

ser

0      mango
1     banana
2     orange
3    chickoo
dtype: object

In [8]:
fruits = ['mango','banana','orange','chickoo']
abc = [1,2,3,4]

ser = pd.Series(fruits)
ser = pd.Series(abc)
ser

0    1
1    2
2    3
3    4
dtype: int64

In [11]:
fruits = ['mango','banana','orange','chickoo']
abc = [1,2]
d = (3,4)

ser = pd.Series((fruits,abc,d))

ser

0    [mango, banana, orange, chickoo]
1                              [1, 2]
2                              (3, 4)
dtype: object

In [12]:
fruits = ['mango','banana','orange','chickoo']

ser = pd.Series(fruits)


ser

0      mango
1     banana
2     orange
3    chickoo
dtype: object

In [13]:
fruits = ['mango','banana','orange','chickoo']

days =  ['mon','tue','wed','thu']


ser2 = pd.Series(data = fruits, index = days)
ser2

mon      mango
tue     banana
wed     orange
thu    chickoo
dtype: object

In [14]:
ser[2]

'orange'

In [15]:
ser2['thu']

'chickoo'

In [16]:
ser2[3]

C:\Users\mayan\AppData\Local\Temp\ipykernel_12448\1801101107.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[3]

'chickoo'

In [17]:
ser3 = pd.Series(data = days, index = fruits)
ser3

mango      mon
banana     tue
orange     wed
chickoo    thu
dtype: object

In [18]:
days_fruits_dict = {'mon':'mango','tue':'banana','wed':'orange','thu':'chickoo'}


dict_series = pd.Series(days_fruits_dict)

dict_series

mon      mango
tue     banana
wed     orange
thu    chickoo
dtype: object

In [19]:
dict_series.values

array(['mango', 'banana', 'orange', 'chickoo'], dtype=object)

In [18]:
dict_series.value_counts

<bound method IndexOpsMixin.value_counts of mon      mango
tue     banana
wed     orange
thu    chickoo
dtype: object>

In [20]:
dict_series= dict_series.str.upper()

In [21]:
dict_series

mon      MANGO
tue     BANANA
wed     ORANGE
thu    CHICKOO
dtype: object

In [21]:
dict_series = dict_series.index.upper()

dict_series

AttributeError: 'Index' object has no attribute 'upper'

In [22]:
dict_series = dict_series.index.str.upper()

dict_series

Index(['MON', 'TUE', 'WED', 'THU'], dtype='object')

In [23]:
emp_dict = {'id':[1,2,3,4,5], 'initials':['mr','mrs','dr','drs','cr'], 'salary':[100,200,300,400,500]}

emp_dict

{'id': [1, 2, 3, 4, 5],
 'initials': ['mr', 'mrs', 'dr', 'drs', 'cr'],
 'salary': [100, 200, 300, 400, 500]}

In [24]:
ser3 = pd.Series(emp_dict)
ser3

id                    [1, 2, 3, 4, 5]
initials       [mr, mrs, dr, drs, cr]
salary      [100, 200, 300, 400, 500]
dtype: object

In [25]:
df = pd.DataFrame(emp_dict)

df

   id initials  salary
0   1       mr     100
1   2      mrs     200
2   3       dr     300
3   4      drs     400
4   5       cr     500

In [26]:
type(df)

pandas.core.frame.DataFrame

In [27]:
df.dtypes

id           int64
initials    object
salary       int64
dtype: object

In [28]:
type(ser)

pandas.core.series.Series

In [38]:
df['id']

0    1
1    2
2    3
3    4
4    5
Name: id, dtype: int64

In [37]:
df['id'][2]

3

In [39]:
print(df[['id','salary']])

   id  salary
0   1     100
1   2     200
2   3     300
3   4     400
4   5     500

In [31]:
type(df['id'])

pandas.core.series.Series

In [27]:
# how to read a data/ file with pandas

In [1]:
import pandas as pd

In [2]:
emp_df = pd.read_csv(D:\Data Analyst Classes\Data for Classes\Python\Data Files\employees.csv)

SyntaxError: invalid syntax (2671712411.py, line 1)

In [3]:
emp_df = pd.read_csv("D:/Data Analyst Classes/Data for Classes/Python/Data Files/employees.csv")

In [4]:
emp_df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales
1000,NaN,NaN,NaN,NaN,90662181,NaN,NaN,NaN

In [5]:
emp_df.head(n=10)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,08-08-2002,6:51 AM,139852,7.524,True,Business Development

In [6]:
emp_df.tail()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales
1000,NaN,NaN,NaN,NaN,90662181,NaN,NaN,NaN

In [7]:
emp_df.head(10)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,08-08-2002,6:51 AM,139852,7.524,True,Business Development

In [3]:
emp_df = pd.read_csv(R"D:\Data Analyst Classes\Data for Classes\Python\Data Files\employees.csv")

emp_df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [9]:
emp3_df = pd.read_csv("D:\\Data Analyst Classes\\Data for Classes\\Python\\Data Files\\employees.csv")
emp3_df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [4]:
emp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1001 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.7+ KB

In [5]:
emp_df.dtypes

First Name            object
Gender                object
Start Date            object
Last Login Time       object
Salary                 int64
Bonus %              float64
Senior Management     object
Team                  object
dtype: object

In [6]:
abc = emp_df.info()

abc

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1001 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.7+ KB

In [7]:
type(abc)

NoneType

In [8]:
emp_df.isnull()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False
1000,True,True,True,True,False,True,True,True

In [9]:
emp_df.isnull().sum()

First Name            68
Gender               146
Start Date             1
Last Login Time        1
Salary                 0
Bonus %                1
Senior Management     68
Team                  44
dtype: int64

In [10]:
emp_df.notnull().sum()

First Name            933
Gender                855
Start Date           1000
Last Login Time      1000
Salary               1001
Bonus %              1000
Senior Management     933
Team                  957
dtype: int64

In [11]:
emp_df.sort_values(by = 'Salary', ascending = False, ).head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1000,NaN,NaN,NaN,NaN,90662181,NaN,NaN,NaN
644,Katherine,Female,8/13/1996,12:21 AM,149908,18.912,False,Finance
429,Rose,Female,5/28/2015,8:40 AM,149903,5.630,False,Human Resources
828,Cynthia,Female,07-12-2006,8:55 AM,149684,7.864,False,Product
186,NaN,Female,2/23/2005,9:50 PM,149654,1.825,NaN,Sales

In [12]:
emp_df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [13]:
emp_df_sort = emp_df.sort_values(by = 'Salary', ascending = False)

emp_df_sort.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1000,NaN,NaN,NaN,NaN,90662181,NaN,NaN,NaN
644,Katherine,Female,8/13/1996,12:21 AM,149908,18.912,False,Finance
429,Rose,Female,5/28/2015,8:40 AM,149903,5.630,False,Human Resources
828,Cynthia,Female,07-12-2006,8:55 AM,149684,7.864,False,Product
186,NaN,Female,2/23/2005,9:50 PM,149654,1.825,NaN,Sales

In [20]:
emp_sorted = emp_df.sort_values(by=['First Name', 'Salary'], ascending=[True, False])

emp_sorted.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
937,Aaron,NaN,1/22/1986,7:39 PM,63126,18.424,False,Client Services
101,Aaron,Male,2/17/2012,10:20 AM,61602,11.849,True,Marketing
327,Aaron,Male,1/29/1994,6:48 PM,58755,5.097,True,Marketing
440,Aaron,Male,7/22/1990,2:53 PM,52119,11.343,True,Client Services
141,Adam,Male,12/24/1990,8:57 PM,110194,14.727,True,Product

In [21]:
emp_df.describe()

             Salary      Bonus %
count  1.001000e+03  1000.000000
mean   1.811432e+05    10.207555
std    2.862881e+06     5.528481
min    3.501300e+04     1.015000
25%    6.266600e+04     5.401750
50%    9.042900e+04     9.838500
75%    1.187530e+05    14.838000
max    9.066218e+07    19.944000

In [14]:
emp_df['Salary'].sum()

181324362

In [15]:
emp_df.T

,0,1,2,3,4,5,6,7,8,9,...,991,992,993,994,995,996,997,998,999,1000
First Name,Douglas,Thomas,Maria,Jerry,Larry,Dennis,Ruby,NaN,Angela,Frances,...,Rose,Anthony,Tina,George,Henry,Phillip,Russell,Larry,Albert,NaN
Gender,Male,Male,Female,Male,Male,Male,Female,Female,Female,Female,...,Female,Male,Female,Male,NaN,Male,Male,Male,Male,NaN
Start Date,08-06-1993,3/31/1996,4/23/1993,03-04-2005,1/24/1998,4/18/1987,8/17/1987,7/20/2015,11/22/2005,08-08-2002,...,8/25/2002,10/16/2011,5/15/1997,6/21/2013,11/23/2014,1/31/1984,5/20/2013,4/20/2013,5/15/2012,NaN
Last Login Time,12:42 PM,6:53 AM,11:17 AM,1:00 PM,4:47 PM,1:35 AM,4:20 PM,10:43 AM,6:29 AM,6:51 AM,...,5:12 AM,8:35 AM,3:53 PM,5:47 PM,6:09 AM,6:30 AM,12:39 PM,4:45 PM,6:24 PM,NaN
Salary,97308,61933,130590,138705,101004,115163,65476,45906,95570,139852,...,134505,112769,56450,98874,132483,42392,96914,60500,129949,90662181
Bonus %,6.945,4.17,11.858,9.34,1.389,10.125,10.012,11.598,18.523,7.524,...,11.051,11.625,19.04,4.479,16.655,19.675,1.421,11.985,10.169,NaN
Senior Management,True,True,False,True,True,False,True,NaN,True,True,...,True,True,True,True,False,False,False,False,True,NaN
Team,Marketing,NaN,Finance,Finance,Client Services,Legal,Product,Finance,Engineering,Business Development,...,Marketing,Finance,Engineering,Marketing,Distribution,Finance,Product,Business Development,Sales,NaN

In [16]:
emp_df['Team'].value_counts()

Team
Client Services         106
Finance                 102
Business Development    101
Marketing                98
Product                  95
Sales                    94
Engineering              92
Human Resources          91
Distribution             90
Legal                    88
Name: count, dtype: int64

In [17]:
emp_df['Team'].value_counts(dropna = True)

Team
Client Services         106
Finance                 102
Business Development    101
Marketing                98
Product                  95
Sales                    94
Engineering              92
Human Resources          91
Distribution             90
Legal                    88
Name: count, dtype: int64

In [30]:
emp_df['Team'].value_counts(dropna = False)

Team
Client Services         106
Finance                 102
Business Development    101
Marketing                98
Product                  95
Sales                    94
Engineering              92
Human Resources          91
Distribution             90
Legal                    88
NaN                      44
Name: count, dtype: int64

In [18]:
emp_df['Team'].value_counts(dropna = False, normalize = True)

Team
Client Services         0.105894
Finance                 0.101898
Business Development    0.100899
Marketing               0.097902
Product                 0.094905
Sales                   0.093906
Engineering             0.091908
Human Resources         0.090909
Distribution            0.089910
Legal                   0.087912
NaN                     0.043956
Name: proportion, dtype: float64

In [19]:
emp_df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [25]:
emp_df[['Company', 'abc']] = 'Google'

emp_df.tail()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company,"(Company, abc)",abc
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Google,Google,Google
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Google,Google,Google
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Google,Google,Google
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Google,Google,Google
1000,NaN,NaN,NaN,NaN,90662181,NaN,NaN,NaN,Google,Google,Google

In [31]:
emp_df.drop(columns=['abc'], inplace = True)
emp_df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company,"(Company, abc)"
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing,Google,Google
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Google,Google
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Google,Google
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance,Google,Google
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Google,Google

In [33]:
emp_df.columns

Index([       'First Name',            'Gender',        'Start Date',
         'Last Login Time',            'Salary',           'Bonus %',
       'Senior Management',              'Team',           'Company',
        ('Company', 'abc')],
      dtype='object')

In [34]:
emp_df.drop(columns=[('Company', 'abc')], inplace = True)
emp_df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing,Google
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Google
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Google
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance,Google
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Google

In [35]:
emp_df['Company']= 'Microsoft'

emp_df.head(9)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing,Microsoft
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Microsoft
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Microsoft
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance,Microsoft
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Microsoft
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal,Microsoft
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product,Microsoft
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance,Microsoft
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering,Microsoft

In [36]:
emp_df['Team'].unique()

array(['Marketing', nan, 'Finance', 'Client Services', 'Legal', 'Product',
       'Engineering', 'Business Development', 'Human Resources', 'Sales',
       'Distribution'], dtype=object)

In [37]:
emp_df['Team'].replace(to_replace = 'Client Services' , value = 'CS').head()

0    Marketing
1          NaN
2      Finance
3      Finance
4           CS
Name: Team, dtype: object

In [40]:
emp_df['Team'].replace(to_replace = NaN , value = 'unknown').head()

NameError: name 'NaN' is not defined

In [41]:
emp_df['Team'].fillna(value = 'unknown').tail()

996                  Finance
997                  Product
998     Business Development
999                    Sales
1000                 unknown
Name: Team, dtype: object

In [42]:
emp_df2 = emp_df.dropna(subset = ['First Name'], how = 'all')

emp_df2.head(9)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing,Microsoft
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Microsoft
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Microsoft
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance,Microsoft
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Microsoft
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal,Microsoft
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product,Microsoft
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering,Microsoft
9,Frances,Female,08-08-2002,6:51 AM,139852,7.524,True,Business Development,Microsoft

In [43]:
emp_df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 933 entries, 0 to 999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             795 non-null    object
 2   Start Date         933 non-null    object
 3   Last Login Time    933 non-null    object
 4   Salary             933 non-null    int64
 5   Bonus %            933 non-null    float64
 6   Senior Management  933 non-null    object
 7   Team               899 non-null    object
 8   Company            933 non-null    object
dtypes: float64(1), int64(1), object(7)
memory usage: 72.9+ KB

In [44]:
emp_df.isnull().sum()

First Name            68
Gender               146
Start Date             1
Last Login Time        1
Salary                 0
Bonus %                1
Senior Management     68
Team                  44
Company                0
dtype: int64

In [45]:
emp_df2.isnull().sum()

First Name             0
Gender               138
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management      0
Team                  34
Company                0
dtype: int64

In [46]:
emp_df10 = emp_df.dropna(subset = ['Team', 'Gender'], how = 'all')

emp_df10.head(9)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing,Microsoft
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Microsoft
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Microsoft
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance,Microsoft
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Microsoft
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal,Microsoft
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product,Microsoft
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance,Microsoft
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering,Microsoft

In [47]:
emp_df10.isnull().sum()

First Name            66
Gender               141
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management     66
Team                  39
Company                0
dtype: int64

In [48]:
emp_df3 = emp_df2.drop_duplicates(subset = ['First Name', 'Team'])

emp_df3.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing,Microsoft
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Microsoft
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Microsoft
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance,Microsoft
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Microsoft

In [49]:
emp_df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 758 entries, 0 to 999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         758 non-null    object
 1   Gender             647 non-null    object
 2   Start Date         758 non-null    object
 3   Last Login Time    758 non-null    object
 4   Salary             758 non-null    int64
 5   Bonus %            758 non-null    float64
 6   Senior Management  758 non-null    object
 7   Team               725 non-null    object
 8   Company            758 non-null    object
dtypes: float64(1), int64(1), object(7)
memory usage: 59.2+ KB

In [50]:
# data filtering


# dataframe[condition]

emp_df['Gender'] == 'Male'

0        True
1        True
2       False
3        True
4        True
        ...
996      True
997      True
998      True
999      True
1000    False
Name: Gender, Length: 1001, dtype: bool

In [51]:
emp_df[emp_df['Gender'] == 'Male']

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing,Microsoft
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Microsoft
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance,Microsoft
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Microsoft
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal,Microsoft
...,...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing,Microsoft
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,Microsoft
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,Microsoft
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,Microsoft
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,Microsoft

In [52]:
cond1 = emp_df['Gender'] == 'Male'

emp_df[cond1].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing,Microsoft
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Microsoft
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance,Microsoft
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Microsoft
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal,Microsoft

In [53]:
cond1 = emp_df['Gender'] == 'Male'
cond2 = emp_df['Salary'] > 100000

emp_df[cond1 and cond2].head()

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [54]:
cond1 = emp_df['Gender'] == 'Male'
cond2 = emp_df['Salary'] > 100000

emp_filter = emp_df[cond1 & cond2]

emp_filter.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance,Microsoft
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Microsoft
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal,Microsoft
12,Brandon,Male,12-01-1980,1:08 AM,112807,17.492,True,Human Resources,Microsoft
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales,Microsoft

In [55]:
emp_filter.info()

<class 'pandas.core.frame.DataFrame'>
Index: 177 entries, 3 to 999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         162 non-null    object
 1   Gender             177 non-null    object
 2   Start Date         177 non-null    object
 3   Last Login Time    177 non-null    object
 4   Salary             177 non-null    int64
 5   Bonus %            177 non-null    float64
 6   Senior Management  162 non-null    object
 7   Team               167 non-null    object
 8   Company            177 non-null    object
dtypes: float64(1), int64(1), object(7)
memory usage: 13.8+ KB

In [56]:
cond1 = emp_df['Senior Management'] == "True"
cond2 = emp_df['Bonus %'] >= 10

emp_df[cond1 | cond2].head(10)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Microsoft
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal,Microsoft
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product,Microsoft
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance,Microsoft
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering,Microsoft
10,Louise,Female,08-12-1980,9:01 AM,63241,15.132,True,NaN,Microsoft
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal,Microsoft
12,Brandon,Male,12-01-1980,1:08 AM,112807,17.492,True,Human Resources,Microsoft
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance,Microsoft
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services,Microsoft

In [57]:
cond3 = emp_df['Salary'] >= 120000

emp_df[(cond1 | cond2) & cond3].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Microsoft
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services,Microsoft
28,Terry,Male,11/27/1981,6:30 PM,124008,13.464,True,Client Services,Microsoft
36,Rachel,Female,2/16/2009,8:47 PM,142032,12.599,False,Business Development,Microsoft
42,Beverly,Female,09-09-1998,8:26 PM,121918,15.835,False,Legal,Microsoft

In [58]:
cond4=emp_df['Team']=='Legal'
cond5=emp_df['Team']=='Product'   
cond6=emp_df['Team']=='Finance'

emp_df[cond4|cond5|cond6].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Microsoft
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance,Microsoft
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal,Microsoft
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product,Microsoft
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance,Microsoft

In [59]:
# isin operator

cond = emp_df['Team'].isin(['Legal','Product','Finance'])

emp_df[cond].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Microsoft
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance,Microsoft
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal,Microsoft
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product,Microsoft
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance,Microsoft

In [60]:
cond7 = emp_df['Bonus %'].between(2,5)

emp_df[~cond7].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing,Microsoft
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Microsoft
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance,Microsoft
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Microsoft
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal,Microsoft

In [61]:
cond8 = emp_df ['Bonus %'].isin(range(2,5))

emp_df[cond8]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
815,Maria,NaN,1/18/1986,8:36 PM,106562,4.0,False,Human Resources,Microsoft

In [62]:
emp_50 = emp_df.head(50)

emp_50.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing,Microsoft
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Microsoft
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,Microsoft
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance,Microsoft
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,Microsoft

In [63]:
cond9 = emp_50['Bonus %'].between(2,5)

emp_50[cond9]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Microsoft
20,Lois,NaN,4/22/1995,7:18 PM,64714,4.934,True,Legal,Microsoft
40,Michael,Male,10-10-2008,11:25 AM,99283,2.665,True,Distribution,Microsoft
49,Chris,NaN,1/24/1980,12:13 PM,113590,3.055,False,Sales,Microsoft

In [64]:
emp_df.head(50)[cond7]

C:\Users\mayan\AppData\Local\Temp\ipykernel_22812\4115423021.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  emp_df.head(50)[cond7]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Microsoft
20,Lois,NaN,4/22/1995,7:18 PM,64714,4.934,True,Legal,Microsoft
40,Michael,Male,10-10-2008,11:25 AM,99283,2.665,True,Distribution,Microsoft
49,Chris,NaN,1/24/1980,12:13 PM,113590,3.055,False,Sales,Microsoft

In [66]:
emp_df[cond7].head(200)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Company
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,Microsoft
20,Lois,NaN,4/22/1995,7:18 PM,64714,4.934,True,Legal,Microsoft
40,Michael,Male,10-10-2008,11:25 AM,99283,2.665,True,Distribution,Microsoft
49,Chris,NaN,1/24/1980,12:13 PM,113590,3.055,False,Sales,Microsoft
60,Paula,NaN,11/23/2005,2:01 PM,48866,4.271,False,Distribution,Microsoft
...,...,...,...,...,...,...,...,...,...
943,Wayne,Male,09-08-2006,11:09 AM,67471,2.728,False,Engineering,Microsoft
961,Antonio,NaN,6/18/1989,9:37 PM,103050,3.050,False,Legal,Microsoft
976,Denise,Female,10/19/1992,5:42 AM,137954,4.195,True,Legal,Microsoft
989,Justin,NaN,02-10-1991,4:58 PM,38344,3.794,False,Legal,Microsoft
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing,Microsoft

In [67]:
emp_df = pd.read_csv("D:/Data Analyst Classes/Data for Classes/Python/Data Files/employees.csv")

In [68]:
emp_df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [69]:
emp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1001 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.7+ KB

In [70]:
# to covert in date time format

pd.to_datetime(emp_df['Last Login Time']).dt.time.head()

C:\Users\mayan\AppData\Local\Temp\ipykernel_22812\2355120402.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(emp_df['Last Login Time']).dt.time.head()

0    12:42:00
1    06:53:00
2    11:17:00
3    13:00:00
4    16:47:00
Name: Last Login Time, dtype: object

In [73]:
pd.to_datetime(emp_df['Start Date'],format='mixed',
    dayfirst=False,errors='coerce').dt.date.head()

0    1993-08-06
1    1996-03-31
2    1993-04-23
3    2005-03-04
4    1998-01-24
Name: Start Date, dtype: object

In [74]:
pd.to_datetime(emp_df['Start Date'], format='mixed',
    dayfirst=False,errors='coerce').dt.date.isnull().sum()

1

In [75]:
emp_df['Start Date'] = pd.to_datetime(emp_df['Start Date'], format='mixed',
    dayfirst=False,errors='coerce').dt.date

emp_df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,4:47 PM,101004,1.389,True,Client Services

In [76]:
emp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1001 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.7+ KB

In [78]:
emp_df['Last Login Time'] = pd.to_datetime(emp_df['Last Login Time']).dt.time

emp_df.head()

C:\Users\mayan\AppData\Local\Temp\ipykernel_22812\1228335291.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  emp_df['Last Login Time'] = pd.to_datetime(emp_df['Last Login Time']).dt.time

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004,1.389,True,Client Services

In [80]:
emp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1001 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.7+ KB

In [81]:
emp_df['Start Date'].dtypes

dtype('O')

In [82]:
emp_df['Salary'] = emp_df['Salary'].astype('float')
emp_df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308.0,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933.0,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590.0,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705.0,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004.0,1.389,True,Client Services

In [93]:
emp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1001 non-null   float64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(2), object(6)
memory usage: 62.7+ KB

In [83]:
emp_df['Start Date'] = emp_df['Start Date'].astype('datetime64[ns]')

emp_df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308.0,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933.0,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590.0,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705.0,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004.0,1.389,True,Client Services

In [84]:
emp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   datetime64[ns]
 3   Last Login Time    1000 non-null   object
 4   Salary             1001 non-null   float64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 62.7+ KB

In [96]:
cond10 = emp_df['Team']!= 'Finance'

emp_df[cond10].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308.0,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933.0,4.170,True,NaN
4,Larry,Male,1998-01-24,16:47:00,101004.0,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163.0,10.125,False,Legal
6,Ruby,Female,1987-08-17,16:20:00,65476.0,10.012,True,Product

In [97]:
cond11 = emp_df['Team'] == 'Finance'

emp_df[~ cond11].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308.0,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933.0,4.170,True,NaN
4,Larry,Male,1998-01-24,16:47:00,101004.0,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163.0,10.125,False,Legal
6,Ruby,Female,1987-08-17,16:20:00,65476.0,10.012,True,Product

In [98]:
cond7 = emp_df['Bonus %'].between(2,5)

emp_df[~cond7].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308.0,6.945,True,Marketing
2,Maria,Female,1993-04-23,11:17:00,130590.0,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705.0,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004.0,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163.0,10.125,False,Legal

In [99]:
cond1 = emp_df['Senior Management'] == True 
cond2 = emp_df['Bonus %'] >= 10

emp_df[~((cond2) | (cond1))].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
13,Gary,Male,2008-01-27,23:40:00,109831.0,5.831,False,Sales
15,Lillian,Female,2016-06-05,06:09:00,59414.0,1.256,False,Product
16,Jeremy,Male,2010-09-21,05:56:00,90370.0,7.369,False,Human Resources
17,Shawn,Male,1986-12-07,19:45:00,111737.0,6.414,False,Product
19,Donna,Female,2010-07-22,03:48:00,81014.0,1.894,False,Product

In [100]:
emp_df[~((emp_df['Bonus %']>=10) | (emp_df['Senior Management']== True))].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
13,Gary,Male,2008-01-27,23:40:00,109831.0,5.831,False,Sales
15,Lillian,Female,2016-06-05,06:09:00,59414.0,1.256,False,Product
16,Jeremy,Male,2010-09-21,05:56:00,90370.0,7.369,False,Human Resources
17,Shawn,Male,1986-12-07,19:45:00,111737.0,6.414,False,Product
19,Donna,Female,2010-07-22,03:48:00,81014.0,1.894,False,Product

In [101]:
c1 = emp_df['First Name'].isnull()

emp_df[~c1].head(9)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308.0,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933.0,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590.0,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705.0,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004.0,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163.0,10.125,False,Legal
6,Ruby,Female,1987-08-17,16:20:00,65476.0,10.012,True,Product
8,Angela,Female,2005-11-22,06:29:00,95570.0,18.523,True,Engineering
9,Frances,Female,2002-08-08,06:51:00,139852.0,7.524,True,Business Development

In [102]:
c2 = emp_df['First Name'].notnull()

emp_df[c2].head(9)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308.0,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933.0,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590.0,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705.0,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004.0,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163.0,10.125,False,Legal
6,Ruby,Female,1987-08-17,16:20:00,65476.0,10.012,True,Product
8,Angela,Female,2005-11-22,06:29:00,95570.0,18.523,True,Engineering
9,Frances,Female,2002-08-08,06:51:00,139852.0,7.524,True,Business Development

In [103]:
# Axes

# axis = 0 -> rows
# axis =1  -> columns

emp_df.columns

Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
       'Bonus %', 'Senior Management', 'Team'],
      dtype='object')

In [104]:
emp_df.index

RangeIndex(start=0, stop=1001, step=1)

In [105]:
# Q. I want all the data of employees for which we have data for all the fields

# 1. Use dropna and save it to new dataframe - parameter- how- 'any
# 2. use 8 conditions for each column with notnull and then use & operator .

In [106]:
emp_df.notnull

<bound method DataFrame.notnull of      First Name  Gender Start Date Last Login Time      Salary  Bonus %  \
0       Douglas    Male 1993-08-06        12:42:00     97308.0    6.945
1        Thomas    Male 1996-03-31        06:53:00     61933.0    4.170
2         Maria  Female 1993-04-23        11:17:00    130590.0   11.858
3         Jerry    Male 2005-03-04        13:00:00    138705.0    9.340
4         Larry    Male 1998-01-24        16:47:00    101004.0    1.389
...         ...     ...        ...             ...         ...      ...
996     Phillip    Male 1984-01-31        06:30:00     42392.0   19.675
997     Russell    Male 2013-05-20        12:39:00     96914.0    1.421
998       Larry    Male 2013-04-20        16:45:00     60500.0   11.985
999      Albert    Male 2012-05-15        18:24:00    129949.0   10.169
1000        NaN     NaN        NaT             NaT  90662181.0      NaN

     Senior Management                  Team
0                 True             Marketing
1                 True                   NaN
2                False               Finance
3                 True               Finance
4                 True       Client Services
...                ...                   ...
996              False               Finance
997              False               Product
998              False  Business Development
999               True                 Sales
1000               NaN                   NaN

[1001 rows x 8 columns]>

In [107]:
emp_df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308.0,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933.0,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590.0,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705.0,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004.0,1.389,True,Client Services

In [108]:
emp_df.isnull().sum()

First Name            68
Gender               146
Start Date             1
Last Login Time        1
Salary                 0
Bonus %                1
Senior Management     68
Team                  44
dtype: int64

In [109]:
emp_df.isnull().sum(axis =1).head()

0    0
1    1
2    0
3    0
4    0
dtype: int64

In [110]:
emp_df_NN = emp_df[emp_df.isnull().sum(axis =1) == 0]
emp_df_NN.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308.0,6.945,True,Marketing
2,Maria,Female,1993-04-23,11:17:00,130590.0,11.858,False,Finance
3,Jerry,Male,2005-03-04,13:00:00,138705.0,9.340,True,Finance
4,Larry,Male,1998-01-24,16:47:00,101004.0,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163.0,10.125,False,Legal

In [111]:
emp_df_NN.info()

<class 'pandas.core.frame.DataFrame'>
Index: 764 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         764 non-null    object
 1   Gender             764 non-null    object
 2   Start Date         764 non-null    datetime64[ns]
 3   Last Login Time    764 non-null    object
 4   Salary             764 non-null    float64
 5   Bonus %            764 non-null    float64
 6   Senior Management  764 non-null    object
 7   Team               764 non-null    object
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 53.7+ KB

In [112]:
emp_df = pd.read_csv(R"D:\Data Analyst Classes\Data for Classes\Python\Data Files\employees.csv", parse_dates = ['Start Date'], date_format = "mixed")

emp_df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,4:47 PM,101004,1.389,True,Client Services

In [113]:
emp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   datetime64[ns]
 3   Last Login Time    1000 non-null   object
 4   Salary             1001 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 62.7+ KB

In [114]:
# Indexing
# by default - 0 to n

In [115]:
emp_df.set_index('First Name').head()

,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
First Name,,,,,,,
Douglas,Male,1993-08-06,12:42 PM,97308,6.945,True,Marketing
Thomas,Male,1996-03-31,6:53 AM,61933,4.170,True,NaN
Maria,Female,1993-04-23,11:17 AM,130590,11.858,False,Finance
Jerry,Male,2005-03-04,1:00 PM,138705,9.340,True,Finance
Larry,Male,1998-01-24,4:47 PM,101004,1.389,True,Client Services

In [116]:
emp_df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,4:47 PM,101004,1.389,True,Client Services

In [117]:
import pandas as pd

In [118]:
pok = pd.read_csv(R"D:\Data Analyst Classes\Data for Classes\Python\Data Files\pokemon.csv")

pok.head()

      Pokemon   Type
0   Bulbasaur  Grass
1     Ivysaur  Grass
2    Venusaur  Grass
3  Charmander   Fire
4  Charmeleon   Fire

In [119]:
pok.loc['Bulbasaur']

KeyError: 'Bulbasaur'

In [ ]:
pok.loc[3]

In [ ]:
pok.set_index(keys = 'Pokemon', inplace = True)

In [ ]:
pok.head()

In [ ]:
pok.loc['Bulbasaur']

In [ ]:
pok.iloc[1]

In [120]:
nba = pd.read_csv(R"D:\Data Analyst Classes\Data for Classes\Python\Data Files\nba.csv")

nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [121]:
nba.loc[4]

Name         Jonas Jerebko
Team        Boston Celtics
Number                 8.0
Position                PF
Age                   29.0
Height                6-10
Weight               231.0
College                NaN
Salary           5000000.0
Name: 4, dtype: object

In [122]:
nba.loc[3:10]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0

In [123]:
nba.loc[3:10, ['Name','Team','Salary']]

               Name            Team      Salary
3       R.J. Hunter  Boston Celtics   1148640.0
4     Jonas Jerebko  Boston Celtics   5000000.0
5      Amir Johnson  Boston Celtics  12000000.0
6     Jordan Mickey  Boston Celtics   1170960.0
7      Kelly Olynyk  Boston Celtics   2165160.0
8      Terry Rozier  Boston Celtics   1824360.0
9      Marcus Smart  Boston Celtics   3431040.0
10  Jared Sullinger  Boston Celtics   2569260.0

In [124]:
nba = nba.sort_values(by = 'Salary', ascending = False)

nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000.0
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,NaN,22359364.0
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0

In [125]:
nba.loc[3:10]

Empty DataFrame
Columns: [Name, Team, Number, Position, Age, Height, Weight, College, Salary]
Index: []

In [126]:
nba.iloc[3:10]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,NaN,22359364.0
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695.0
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622.0
164,Derrick Rose,Chicago Bulls,1.0,PG,27.0,6-3,190.0,Memphis,20093064.0
349,Dwyane Wade,Miami Heat,3.0,SG,34.0,6-4,220.0,Marquette,20000000.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0

In [127]:
nba.loc[:3:3]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000.0
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,NaN,22359364.0
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
174,Kevin Love,Cleveland Cavaliers,0.0,PF,27.0,6-10,251.0,UCLA,19689000.0
...,...,...,...,...,...,...,...,...,...
246,Clint Capela,Houston Rockets,15.0,PF,22.0,6-10,240.0,NaN,1242720.0
267,P.J. Hairston,Memphis Grizzlies,19.0,SF,23.0,6-6,230.0,North Carolina,1201440.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
105,C.J. Wilcox,Los Angeles Clippers,30.0,SG,25.0,6-5,195.0,Washington,1159680.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0

In [128]:
nba.iloc[:3]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000.0
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0

In [129]:
nba.iloc[:3, :5]

                Name                 Team  Number Position   Age
109      Kobe Bryant   Los Angeles Lakers    24.0       SF  37.0
169     LeBron James  Cleveland Cavaliers    23.0       SF  31.0
33   Carmelo Anthony      New York Knicks     7.0       SF  32.0

In [130]:
nba.head(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000.0
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,NaN,22359364.0
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695.0
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622.0
164,Derrick Rose,Chicago Bulls,1.0,PG,27.0,6-3,190.0,Memphis,20093064.0
349,Dwyane Wade,Miami Heat,3.0,SG,34.0,6-4,220.0,Marquette,20000000.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0

In [131]:
nba.loc[251:294, 'Name':'Age']

                  Name                   Team  Number Position   Age
251      Dwight Howard        Houston Rockets    12.0        C  30.0
339         Chris Bosh             Miami Heat     1.0       PF  32.0
100         Chris Paul   Los Angeles Clippers     3.0       PG  31.0
414       Kevin Durant  Oklahoma City Thunder    35.0       SF  27.0
164       Derrick Rose          Chicago Bulls     1.0       PG  27.0
349        Dwyane Wade             Miami Heat     3.0       SG  34.0
294  LaMarcus Aldridge      San Antonio Spurs    12.0       PF  30.0

In [132]:
nba.iloc[9,2]

12.0

In [133]:
df = pd.read_clipboard()

df

Empty DataFrame
Columns: [=, 0]
Index: []

In [134]:
df.sort_values('Volume', ascending = False).head()

KeyError: 'Volume'

In [135]:
bond = pd.read_csv(R"D:\Data Analyst Classes\Data for Classes\Python\Data Files\jamesbond.csv")

bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [136]:
bond.set_index('Film', inplace = True)
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [137]:
bond.loc['Dr. No']

Year                          1962
Actor                 Sean Connery
Director             Terence Young
Box Office                   448.8
Budget                         7.0
Bond Actor Salary              0.6
Name: Dr. No, dtype: object

In [139]:
bond.loc['Goldfinger','Box Office'] = 820

bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.0,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [140]:
bond.loc[bond['Year']< 1967,'Director'] = 'Christopher'

bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Christopher,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Christopher,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Christopher,820.0,18.6,3.2
Thunderball,1965,Sean Connery,Christopher,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [176]:
bond = pd.read_csv(R"D:\Data Analyst Classes\Data for Classes\Python\Data Files\jamesbond.csv")

bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [177]:
bond.axes

[RangeIndex(start=0, stop=26, step=1),
 Index(['Film', 'Year', 'Actor', 'Director', 'Box Office', 'Budget',
        'Bond Actor Salary'],
       dtype='object')]

In [178]:
bond.rename(mapper ={'Film':'Movie', 'Box Office': 'Revenue', 'Bond Actor Salary': 'Salary'}, axis =1).head()

,Movie,Year,Actor,Director,Revenue,Budget,Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [179]:
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [180]:
bond.rename(columns={'Film':'Movie', 'Box Office': 'Revenue', 'Bond Actor Salary': 'Salary'}).head()

,Movie,Year,Actor,Director,Revenue,Budget,Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [181]:
bond.sample(n =10)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8

In [182]:
bond.sample(n =10)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1

In [183]:
bond.sample(n =10, random_state = 2)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1

In [184]:
bond.sample(n =10, random_state = 2)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1

In [185]:
bond.sample(random_state = 2)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5

In [186]:
bond.sample( n=12, random_state = 2)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [187]:
bond.sample( frac = .4, random_state = 2)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1

In [188]:
bond.shape

(26, 7)

In [189]:
bond.shape[0]

26

In [190]:
bond.nlargest( n = 10, columns = 'Box Office')

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [191]:
bond.nsmallest( n = 10, columns = 'Box Office')

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8

In [192]:
bond[bond['Actor'] == 'Daniel Craig']

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [193]:
bond.where(bond['Actor'] == 'Daniel Craig')

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Casino Royale,2006.0,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008.0,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012.0,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015.0,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [194]:
bond.query('Actor == "Daniel Craig"')

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [195]:
bond.loc[25, 'Bond Actor Salary'] = 0

bond

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,0.0

In [196]:
bond.tail()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,0.0

In [197]:
bond.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Film               26 non-null     object
 1   Year               26 non-null     int64
 2   Actor              26 non-null     object
 3   Director           26 non-null     object
 4   Box Office         26 non-null     float64
 5   Budget             26 non-null     float64
 6   Bond Actor Salary  19 non-null     float64
dtypes: float64(3), int64(1), object(3)
memory usage: 1.6+ KB

In [198]:
x = 456.7
y = str(x) 
w = int(round(x))
print(w)
z = y + " M$"
z

457

'456.7 M$'

In [199]:
def cleaning_data(num):
    num = num*0.8
    num = int(num)
    num = str(num) + '-M$'
    
    return num


bond['Box Office'] = bond['Box Office'].apply(cleaning_data)

bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,359-M$,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,435-M$,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,656-M$,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,678-M$,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,252-M$,85.0,NaN

In [200]:
bond['Budget'] = bond['Budget'].apply(cleaning_data)

bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,359-M$,5-M$,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,435-M$,10-M$,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,656-M$,14-M$,3.2
3,Thunderball,1965,Sean Connery,Terence Young,678-M$,33-M$,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,252-M$,68-M$,NaN

In [201]:
bond['Bond Actor Salary'] = bond['Bond Actor Salary'].apply(cleaning_data)

bond.head()

ValueError: cannot convert float NaN to integer

In [1]:
# to fill the nan values with unknown and add currency digits to the numbers in actors salary

In [97]:
import pandas as pd

In [202]:
def cleaning_data(num):
    num = num*0.8
    if pd.isna(num):     # we can also use math.isnan  ( we need to import math librabry), or np.nan (need to import numpy)
        num = 'unknown'
    else:    
        num = int(num)
        num = str(num) + '-M$'
    
    return num


bond['Bond Actor Salary'] = bond['Bond Actor Salary'].apply(cleaning_data)

bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,359-M$,5-M$,0-M$
1,From Russia with Love,1963,Sean Connery,Terence Young,435-M$,10-M$,1-M$
2,Goldfinger,1964,Sean Connery,Guy Hamilton,656-M$,14-M$,2-M$
3,Thunderball,1965,Sean Connery,Terence Young,678-M$,33-M$,3-M$
4,Casino Royale,1967,David Niven,Ken Hughes,252-M$,68-M$,unknown

In [203]:
bond = pd.read_csv(R"D:\Data Analyst Classes\Data for Classes\Python\Data Files\jamesbond.csv")

bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [204]:
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [206]:
bond['abc'] = 'xyz'
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary,abc
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6,xyz
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6,xyz
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2,xyz
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7,xyz
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN,xyz

In [100]:
def deciciding_outcome(row):
    # BO >= 500M , bud <= 20M  --> blockbuster
    # BO >= 500M , bud > 20M  --> Superhit
    # BO < 500M , bud < 20M  --> Hit
    # BO < 500M , bud >= 20M  --> FLOP
    
    if row['Box Office'] >= 500 and row['Budget'] <= 20:
        row['Outcome'] = 'Blockbuster'
        
    elif row['Box Office'] >= 500 and row['Budget'] > 20:
        row['Outcome'] = 'Superhit'
        
    elif row['Box Office'] < 500 and row['Budget'] <= 20:
        row['Outcome'] = 'Hit'
        
    else:
        row['Outcome'] = 'Flop'
        
    return row


bond = bond.apply(deciciding_outcome, axis = 1)
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary,Outcome
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6,Hit
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6,Blockbuster
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2,Blockbuster
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7,Superhit
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN,Flop

In [207]:
# Text Operations


chicago = pd.read_csv(R"D:\Data Analyst Classes\Data for Classes\Python\Data Files\chicago.csv")

chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [208]:
text = ' I live in Pune'

In [209]:
text.upper(), text.lower(), text.title()

(' I LIVE IN PUNE', ' i live in pune', ' I Live In Pune')

In [210]:
chicago['Position Title'] = chicago['Position Title'].lower()

chicago.head()

AttributeError: 'Series' object has no attribute 'lower'

In [211]:
chicago['Position Title'] = chicago['Position Title'].str.lower()

chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",water rate taker,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",police officer,POLICE,$84450.00
2,"AARON, KARINA",police officer,POLICE,$84450.00
3,"AARON, KIMBERLEI R",chief contract expediter,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",civil engineer iv,WATER MGMNT,$106836.00

In [212]:
chicago['Name'] = chicago['Name'].str.title()

chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"Aaron, Elvia J",water rate taker,WATER MGMNT,$90744.00
1,"Aaron, Jeffery M",police officer,POLICE,$84450.00
2,"Aaron, Karina",police officer,POLICE,$84450.00
3,"Aaron, Kimberlei R",chief contract expediter,GENERAL SERVICES,$89880.00
4,"Abad Jr, Vicente M",civil engineer iv,WATER MGMNT,$106836.00

In [213]:
chicago['Name_length'] = chicago['Name'].str.len()

chicago.head()

,Name,Position Title,Department,Employee Annual Salary,Name_length
0,"Aaron, Elvia J",water rate taker,WATER MGMNT,$90744.00,15.0
1,"Aaron, Jeffery M",police officer,POLICE,$84450.00,17.0
2,"Aaron, Karina",police officer,POLICE,$84450.00,14.0
3,"Aaron, Kimberlei R",chief contract expediter,GENERAL SERVICES,$89880.00,19.0
4,"Abad Jr, Vicente M",civil engineer iv,WATER MGMNT,$106836.00,19.0

In [214]:
chicago.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32063 entries, 0 to 32062
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  object
 1   Position Title          32062 non-null  object
 2   Department              32062 non-null  object
 3   Employee Annual Salary  32062 non-null  object
 4   Name_length             32062 non-null  float64
dtypes: float64(1), object(4)
memory usage: 1.2+ MB

In [215]:
chicago['Employee Annual Salary'].describe()

count         32062
unique         1156
top       $87384.00
freq           2394
Name: Employee Annual Salary, dtype: object

In [216]:
chicago['Employee Annual Salary'].mean()

TypeError: can only concatenate str (not "int") to str

In [217]:
chicago.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32063 entries, 0 to 32062
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  object
 1   Position Title          32062 non-null  object
 2   Department              32062 non-null  object
 3   Employee Annual Salary  32062 non-null  object
 4   Name_length             32062 non-null  float64
dtypes: float64(1), object(4)
memory usage: 1.2+ MB

In [218]:
chicago['Employee Annual Salary'] = chicago['Employee Annual Salary'].str.replace('$','')

chicago.head()

,Name,Position Title,Department,Employee Annual Salary,Name_length
0,"Aaron, Elvia J",water rate taker,WATER MGMNT,90744.00,15.0
1,"Aaron, Jeffery M",police officer,POLICE,84450.00,17.0
2,"Aaron, Karina",police officer,POLICE,84450.00,14.0
3,"Aaron, Kimberlei R",chief contract expediter,GENERAL SERVICES,89880.00,19.0
4,"Abad Jr, Vicente M",civil engineer iv,WATER MGMNT,106836.00,19.0

In [219]:
chicago.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32063 entries, 0 to 32062
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  object
 1   Position Title          32062 non-null  object
 2   Department              32062 non-null  object
 3   Employee Annual Salary  32062 non-null  object
 4   Name_length             32062 non-null  float64
dtypes: float64(1), object(4)
memory usage: 1.2+ MB

In [220]:
chicago['Employee Annual Salary'] = chicago['Employee Annual Salary'].astype('int')

chicago.head()

ValueError: invalid literal for int() with base 10: '90744.00'

In [221]:
chicago.isnull().sum()

Name                      1
Position Title            1
Department                1
Employee Annual Salary    1
Name_length               1
dtype: int64

In [222]:
chicago.tail()

,Name,Position Title,Department,Employee Annual Salary,Name_length
32058,"Zygowicz, Peter J",police officer,POLICE,87384.00,18.0
32059,"Zymantas, Mark E",police officer,POLICE,84450.00,17.0
32060,"Zyrkowski, Carlo E",police officer,POLICE,87384.00,19.0
32061,"Zyskowski, Dariusz",chief data base analyst,DoIT,113664.00,19.0
32062,NaN,NaN,NaN,NaN,NaN

In [223]:
chicago.dropna(how = 'all', inplace = True)

chicago.tail()

,Name,Position Title,Department,Employee Annual Salary,Name_length
32057,"Zygadlo, Michael J",frm of machinists - automotive,GENERAL SERVICES,99528.00,19.0
32058,"Zygowicz, Peter J",police officer,POLICE,87384.00,18.0
32059,"Zymantas, Mark E",police officer,POLICE,84450.00,17.0
32060,"Zyrkowski, Carlo E",police officer,POLICE,87384.00,19.0
32061,"Zyskowski, Dariusz",chief data base analyst,DoIT,113664.00,19.0

In [224]:
chicago['Employee Annual Salary'] = chicago['Employee Annual Salary'].astype('float').astype('int')

chicago.head()

,Name,Position Title,Department,Employee Annual Salary,Name_length
0,"Aaron, Elvia J",water rate taker,WATER MGMNT,90744,15.0
1,"Aaron, Jeffery M",police officer,POLICE,84450,17.0
2,"Aaron, Karina",police officer,POLICE,84450,14.0
3,"Aaron, Kimberlei R",chief contract expediter,GENERAL SERVICES,89880,19.0
4,"Abad Jr, Vicente M",civil engineer iv,WATER MGMNT,106836,19.0

In [227]:
chicago['Employee Annual Salary'].mean()

80204.11786538581

In [229]:
chicago.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32062 entries, 0 to 32061
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    32062 non-null  object
 1   Position Title          32062 non-null  object
 2   Department              32062 non-null  object
 3   Employee Annual Salary  32062 non-null  int32
 4   Name_length             32062 non-null  float64
dtypes: float64(1), int32(1), object(3)
memory usage: 1.3+ MB

In [230]:
chicago.describe()

       Employee Annual Salary   Name_length
count            32062.000000  32062.000000
mean             80204.117865     17.187044
std              25098.387386      2.523272
min                  0.000000      8.000000
25%              72862.000000     15.000000
50%              84450.000000     17.000000
75%              93240.000000     19.000000
max             300000.000000     32.000000

In [231]:
chicago['Department'] = chicago['Department'].str.replace('MGMNT', 'MANAGEMENT')

chicago.head()

,Name,Position Title,Department,Employee Annual Salary,Name_length
0,"Aaron, Elvia J",water rate taker,WATER MANAGEMENT,90744,15.0
1,"Aaron, Jeffery M",police officer,POLICE,84450,17.0
2,"Aaron, Karina",police officer,POLICE,84450,14.0
3,"Aaron, Kimberlei R",chief contract expediter,GENERAL SERVICES,89880,19.0
4,"Abad Jr, Vicente M",civil engineer iv,WATER MANAGEMENT,106836,19.0

In [232]:
chicago[chicago['Department'].str.contains('FI')].tail()

,Name,Position Title,Department,Employee Annual Salary,Name_length
32027,"Zullo, John J",firefighter,FIRE,94530,14.0
32037,"Zuniga, Vicente",firefighter-emt,FIRE,89568,16.0
32039,"Zupan, Bill M",lieutenant-emt,FIRE,107592,14.0
32046,"Zurek, Mary H",senior public information officer,FINANCE,83340,14.0
32053,"Zwolfer, Matthew W",firefighter-emt,FIRE,92682,19.0

In [233]:
chicago[chicago['Department'].str.startswith('FI')].tail()

,Name,Position Title,Department,Employee Annual Salary,Name_length
32027,"Zullo, John J",firefighter,FIRE,94530,14.0
32037,"Zuniga, Vicente",firefighter-emt,FIRE,89568,16.0
32039,"Zupan, Bill M",lieutenant-emt,FIRE,107592,14.0
32046,"Zurek, Mary H",senior public information officer,FINANCE,83340,14.0
32053,"Zwolfer, Matthew W",firefighter-emt,FIRE,92682,19.0

In [234]:
chicago[chicago['Department'].str.endswith('CE')].head()

,Name,Position Title,Department,Employee Annual Salary,Name_length
1,"Aaron, Jeffery M",police officer,POLICE,84450,17.0
2,"Aaron, Karina",police officer,POLICE,84450,14.0
11,"Abbate, Terry M",police officer,POLICE,90618,16.0
13,"Abbott, Lynise M",clerk iii,POLICE,46896,17.0
15,"Abdallah, Zaid",police officer,POLICE,74028,15.0

In [235]:
chicago['Name'].str.split(',', expand = True).head()

         0              1
0    Aaron        Elvia J
1    Aaron      Jeffery M
2    Aaron         Karina
3    Aaron    Kimberlei R
4  Abad Jr      Vicente M

In [236]:
chicago[['First_Name', 'Last_Name']] = chicago['Name'].str.split(',', expand = True)

chicago.head()

,Name,Position Title,Department,Employee Annual Salary,Name_length,First_Name,Last_Name
0,"Aaron, Elvia J",water rate taker,WATER MANAGEMENT,90744,15.0,Aaron,Elvia J
1,"Aaron, Jeffery M",police officer,POLICE,84450,17.0,Aaron,Jeffery M
2,"Aaron, Karina",police officer,POLICE,84450,14.0,Aaron,Karina
3,"Aaron, Kimberlei R",chief contract expediter,GENERAL SERVICES,89880,19.0,Aaron,Kimberlei R
4,"Abad Jr, Vicente M",civil engineer iv,WATER MANAGEMENT,106836,19.0,Abad Jr,Vicente M

In [56]:
# how to alter index postions of  columns in a dataframe  --- interview question

# how to split the words after second space  -- interview question

In [237]:
chicago['postiton_len'] = chicago['Position Title'].str.len()
chicago.head()

,Name,Position Title,Department,Employee Annual Salary,Name_length,First_Name,Last_Name,postiton_len
0,"Aaron, Elvia J",water rate taker,WATER MANAGEMENT,90744,15.0,Aaron,Elvia J,16
1,"Aaron, Jeffery M",police officer,POLICE,84450,17.0,Aaron,Jeffery M,14
2,"Aaron, Karina",police officer,POLICE,84450,14.0,Aaron,Karina,14
3,"Aaron, Kimberlei R",chief contract expediter,GENERAL SERVICES,89880,19.0,Aaron,Kimberlei R,24
4,"Abad Jr, Vicente M",civil engineer iv,WATER MANAGEMENT,106836,19.0,Abad Jr,Vicente M,17

In [238]:
chicago.sort_values(by ='postiton_len', ascending = False).head()

,Name,Position Title,Department,Employee Annual Salary,Name_length,First_Name,Last_Name,postiton_len
24488,"Rodriguez, Jun",general manager of grounds and terminal facili...,AVIATION,110088,15.0,Rodriguez,Jun,50
24525,"Rodriguez, Ralph",supervising rehabilitation construction specia...,COMMUNITY DEVELOPMENT,79596,17.0,Rodriguez,Ralph,50
6616,"Dejesus, Carol A",administrative asst to deputy corporation counsel,LAW,72492,17.0,Dejesus,Carol A,49
13234,"Jackson, Christine",administrative asst to deputy corporation counsel,LAW,83340,19.0,Jackson,Christine,49
18331,"Mcgregor, Lorraine",administrative asst to deputy corporation counsel,LAW,79596,19.0,Mcgregor,Lorraine,49

In [239]:
chicago['Position Title'].str.split(' ', expand = True).head()

        0         1          2     3     4     5     6     7     8
0   water      rate      taker  None  None  None  None  None  None
1  police   officer       None  None  None  None  None  None  None
2  police   officer       None  None  None  None  None  None  None
3   chief  contract  expediter  None  None  None  None  None  None
4   civil  engineer         iv  None  None  None  None  None  None

In [240]:
chicago['Position Title'].str.split(' ', expand = True, n=1).head()

        0                   1
0   water          rate taker
1  police             officer
2  police             officer
3   chief  contract expediter
4   civil         engineer iv

In [241]:
chicago[['Postion First title', 'Position Other title']] = chicago['Position Title'].str.split(' ', expand = True, n=1)

chicago.head()

,Name,Position Title,Department,Employee Annual Salary,Name_length,First_Name,Last_Name,postiton_len,Postion First title,Position Other title
0,"Aaron, Elvia J",water rate taker,WATER MANAGEMENT,90744,15.0,Aaron,Elvia J,16,water,rate taker
1,"Aaron, Jeffery M",police officer,POLICE,84450,17.0,Aaron,Jeffery M,14,police,officer
2,"Aaron, Karina",police officer,POLICE,84450,14.0,Aaron,Karina,14,police,officer
3,"Aaron, Kimberlei R",chief contract expediter,GENERAL SERVICES,89880,19.0,Aaron,Kimberlei R,24,chief,contract expediter
4,"Abad Jr, Vicente M",civil engineer iv,WATER MANAGEMENT,106836,19.0,Abad Jr,Vicente M,17,civil,engineer iv

In [242]:
chicago['Last_Name'].values.tolist()

['  Elvia J',
 '  Jeffery M',
 '  Karina',
 '  Kimberlei R',
 '  Vicente M',
 '  Anabel',
 '  Emmanuel',
 '  Reece E',
 '  Christopher',
 '  Robert J',
 '  James J',
 '  Terry M',
 '  Betty L',
 '  Lynise M',
 '  William J',
 '  Zaid',
 '  Abdalmahd',
 '  Aref R',
 '  Aziz',
 '  Ali',
 '  Muhammad A',
 '  Daniel N',
 '  Kevin',
 '  Lakenya N',
 '  Rashad J',
 '  Mudhar',
 '  Tahir',
 '  Abuubaida',
 '  Jason V',
 '  Earl S',
 '  Timothy',
 '  Adewole A',
 '  Patrick',
 '  Hassan A',
 '  Girley T',
 '  Godwin K',
 '  Nancy A',
 '  Anna A',
 '  Danielle T',
 '  Henry L',
 '  John E',
 '  Samuel A',
 '  Mark A',
 '  Dilan',
 '  Edwin',
 '  Roberto J',
 '  Rosita',
 '  Victor',
 '  Victor',
 '  Floyd',
 '  Kenneth L',
 '  Mohammed G',
 '  Elias',
 '  Awwad',
 '  Mohammad',
 '  Ahmad H',
 '  Abdalla H',
 '  Anthony D',
 '  Jennifer A',
 '  Thomas J',
 '  Michael G',
 '  Nicholas B',
 '  Mary K',
 '  Aaron F',
 '  Alejandro R',
 '  Bienvenido',
 '  Clarissa',
 '  Edward',
 '  Edwin C',
 '  Elias M',
 '  Eric',
 '  Gilbert',
 '  Ilia',
 '  Janete',
 '  Jason M',
 '  Javier',
 '  Jeff',
 '  Josue',
 '  Manuel A',
 '  Marco A',
 '  Marisol',
 '  Martin J',
 '  Mike',
 '  Nadine M',
 '  Rafael',
 '  Juan C',
 '  Anthony E',
 '  Amber L',
 '  Lisa S',
 '  Scott R',
 '  Michael A',
 '  Qiana D',
 '  Jaime A',
 '  Jesse A',
 '  Mark',
 '  Martha A',
 '  Michele D',
 '  Natalie',
 '  Pablo S',
 '  Rosa M',
 '  Anthony E',
 '  Zaireh',
 '  Kenneth R',
 '  Steven',
 '  Audrey E',
 '  Jan',
 '  Lawrence M',
 '  Pedro',
 '  Simon P',
 '  Jeffrey S',
 '  Matthew W',
 '  Michael A',
 '  Jeffrey W',
 '  Richard',
 '  Craig W',
 '  David E',
 '  Deanie M',
 '  Delrice',
 '  Denis H',
 '  Dwayne D',
 '  Warren',
 '  Erwin',
 '  Eula M',
 '  Gary W',
 '  Gregory M',
 '  Gregory W',
 '  Harold',
 '  James W',
 '  Jerry M',
 '  John W',
 '  Jerry J',
 '  Robert',
 '  Leah',
 '  Marjorie E',
 '  Matthew',
 '  Michael A',
 '  Michael J',
 '  Olivia I',
 '  Quan R',
 '  Quenjana',
 '  Raymond T',
 '  Reginald K',
 '  Robert L',
 '  Rosita',
 '  Ryan',
 '  Sheryll A',
 '  Stanley',
 '  Tanera C',
 '  Cheearease R',
 '  Timothy J',
 '  Vicky M',
 '  Nenita P',
 '  David G',
 '  Tommy W',
 '  Vincenzo',
 '  Marc',
 '  Latasha D',
 '  Lewis',
 '  Mark A',
 '  Benjamin B',
 '  James P',
 '  James P',
 '  Ibilola I',
 '  Nikte E',
 '  Joy A',
 '  Bruce E',
 '  Mohamed K',
 '  Emmanuel S',
 '  Kareem A',
 '  Horatio A',
 '  Mojirola M',
 '  Brittany L',
 '  Kerri M',
 '  Marc D',
 '  William J',
 '  Laura R',
 '  Tracy L',
 '  Joseph D',
 '  Elizabeth U',
 '  Walter S',
 '  John J',
 '  Cheri A',
 '  John P',
 '  Mahir A',
 '  Nayyar',
 '  Bulent B',
 '  Lawrence',
 '  Laura J',
 '  Antonio E',
 '  Joseph J',
 '  Michael A',
 '  Hector I',
 '  Mario',
 '  Eduardo',
 '  Edwin',
 '  Fernan S',
 '  Juanito S',
 '  Gilbert Glenn',
 '  Alex',
 '  Braulio',
 '  Luis A',
 '  Phillip R',
 '  William M',
 '  Alfredo',
 '  Efrain',
 '  Elma M',
 '  Esther',
 '  Evaristo P',
 '  Irene',
 '  Jesus D',
 '  Robert',
 '  Juanita',
 '  Juanita M',
 '  Karina D',
 '  Louis',
 '  Luis',
 '  Ray R',
 '  Ricardo L',
 '  Robert',
 '  Horacio',
 '  Jesus',
 '  Juan A',
 '  Linda M',
 '  Maria C',
 '  Saul',
 '  John P',
 '  Megan E',
 '  Alex',
 '  Anthony J',
 '  Enrique',
 '  Guadalupe',
 '  Guadalupe G',
 '  Joseph R',
 '  Juan M',
 '  Kevin',
 '  Julian J',
 '  Pablo',
 '  Ramiro',
 '  Robert J',
 '  Tanya L',
 '  Kofi',
 '  Alexander E',
 '  Dory E',
 '  Michael J',
 '  Patrick J',
 '  Scott E',
 '  Sean',
 '  Michael L',
 '  Margaret L',
 '  Fadi M',
 '  Farooq',
 '  Hoorya',
 '  Ammar E',
 '  Khalid',
 '  Mohammad A',
 '  Mohammed K',
 '  Nafees',
 '  Quazi S',
 '  Rizwana P',
 '  Shahrukh Z',
 '  Syed',
 '  Cecilia T',
 '  Abraham A',
 '  Bradley K',
 '  Catherine',
 '  Clora M',
 '  Lawrence J',
 '  Edmundo R',
 '  James',
 '  Amy',
 '  Sal N',
 '  Zahid N',
 '  Camuhoo R',
 '  Linda',
 '  Edward G',
 '  Mark S',
 '  Derec A',
 '  Willie L',
 '  Saeed',
 '  Syed J',
 '  Ayokunle',
 '  Christopher A',
 '  Grace O',
 '  Daryl',
 '  Kimberly L',
 '  Lisa',
 '  Lou Ann',
 '  Monica E',
 '  Robin G',
 '  Anthony J',
 '  Steven O',
 '  Thomas',
 '  Hasan M',
 '  Hassan',
 '  Mahasin I',
 '  Rasheedah K',
 '  Roberto G',
 '  Syed S',
 '  Jose E',
 '  Oscar',
 '  Robert',
 '  Brian',
 '  Cheri',
 '  Elizabeth',
 '  Michael R',
 '  Robert A',
 '  Sandra',
 '  Sharon',
 '  Luis J',
 '  Frank J',
 '  Fares',
 '  Marc N',
 '  Verbena S',
 '  Alberto S',
 '  Fabian',
 '  Frank J',
 '  Saul B',
 '  Donna',
 '  Louis',
 '  Donna M',
 '  Richard A',
 '  Raymond M',
 '  Hector F',
 '  Daniel R',
 '  Dawn M',
 '  Keith E',
 '  Joseph A',
 '  David A',
 '  Jose P',
 '  Ruben',
 '  Elizabeth',
 '  Jovita L',
 '  Rosio',
 '  Celia',
 '  Ramiro',
 '  Angel G',
 '  Eliasard',
 '  Antoinette',
 '  David E',
 '  Guadalupe R',
 '  Victor A',
 '  Joseph',
 '  Gil A',
 '  Carlos J',
 '  J F',
 '  Martha S',
 '  Jacob M',
 '  Jeffrey S',
 '  Jennifer L',
 '  Nabil K',
 '  James P',
 '  Roberto S',
 '  Samuel M',
 '  David',
 '  Arturo M',
 '  Cristina G',
 '  Jesse',
 '  Luis F',
 '  George',
 '  Jesus',
 '  Ana I',
 '  Joseph',
 '  Christine L',
 '  Robert W',
 '  Adam S',
 '  Michelene A',
 '  Calvin',
 '  Clemmie',
 '  Conrad E',
 '  Dana',
 '  Darius Q',
 '  Darlene',
 '  Doris A',
 '  Earl',
 '  James P',
 '  Gene I',
 '  Kimberly T',
 '  Larron H',
 '  Lorie J',
 '  Mark A',
 '  Mary F',
 '  Patricia L',
 '  Racquel L',
 '  Rochelle D',
 '  Ross J',
 '  Samuel M',
 '  Sarah B',
 '  Wendy R',
 '  Elena',
 '  Tena A',
 '  Hector',
 '  Josephjam S',
 '  Joseph S',
 '  Bernardo',
 '  Gerardo F',
 '  Fred T',
 '  Scott',
 '  Paul R',
 '  Linda D',
 '  Brenda L',
 '  Tiara M',
 '  Joel S',
 '  Jonathan T',
 '  Lisa M',
 '  Richard',
 '  Hasan M',
 '  Mohamad H',
 '  Armanda',
 '  Erminio',
 '  Bilal R',
 '  Angel R',
 '  Felix',
 '  Vilma R',
 '  Fari',
 '  Javed',
 '  Yasmine M',
 '  Mohammed',
 '  Peter A',
 '  Rocco J',
 '  Shahrukh',
 '  Syed H',
 '  Syed S',
 '  Carolyn',
 '  Matthew L',
 '  Anthony',
 '  Nick',
 '  Robert R',
 '  Achen J',
 '  Alphonso J',
 '  Andre G',
 '  Annette D',
 '  Antonio W',
 '  Cora I',
 '  Cassandra',
 '  Clinton S',
 '  Craig M',
 '  Dalphine',
 '  Daniel H',
 '  Daniel J',
 '  David',
 '  Deborah A',
 '  Denotra',
 '  Derrick',
 '  Derrick D',
 '  Dominique',
 '  Donnie',
 '  Elizabeth',
 '  Gloria',
 '  Gordon K',
 '  Henry C',
 '  James W',
 '  Jeffrey W',
 '  Jonathan E',
 '  Keith A',
 '  Kevin C',
 '  Kevin M',
 '  Lajeune R',
 '  Laquetia L',
 '  La Shawnda',
 '  Marie',
 '  Mark D',
 '  Melvin',
 '  Michael J',
 '  Michael L',
 '  Monica J',
 '  Myra B',
 '  Najja T',
 '  Peter B',
 '  Phoebe',
 '  Raymond G',
 '  Regan J',
 '  Richard',
 '  Robert',
 '  Robert G',
 '  Robert L',
 '  Ruth B',
 '  Ryan M',
 '  Ryshon C',
 '  Sahid J',
 '  Sandra',
 '  Sage',
 '  Terry L',
 '  Timothy',
 '  Timothy M',
 '  Tyree D',
 '  Verdie P',
 '  Vincent',
 '  Wanda L',
 '  William',
 '  William L',
 '  Hattie',
 '  Steve C',
 '  Allyson M',
 '  Jacob M',
 '  John L',
 '  Paul W',
 '  David J',
 '  Philip',
 '  Eduardo',
 '  Francisco J',
 '  Jesus',
 '  Jose A',
 '  Monica',
 '  Theresa A',
 '  Yolanda M',
 '  Alejandro',
 '  Carmen',
 '  Cecilia',
 '  Sidronio',
 '  Sonia',
 '  Tomas',
 '  Lloyd M',
 '  Filiberto',
 '  Joshua',
 '  Manuel',
 '  Olga N',
 '  Jose',
 '  Eyad J',
 '  Sami J',
 '  Salvatore D',
 '  George',
 '  Konstantines M',
 '  Armando',
 '  Eduardo',
 '  Javier',
 '  Kenneth',
 '  Laura K',
 '  Mario A',
 '  Christopher B',
 '  Edward',
 '  Gregory P',
 '  J B',
 '  Jessica M',
 '  Joaquin',
 '  Shawn P',
 '  Vincent S',
 '  Stuart H',
 '  David P',
 '  Evaristo P',
 '  Mary E',
 '  Etta E',
 '  Gloria',
 '  Nicole T',
 '  Lazaro',
 '  Rafael',
 '  Adam J',
 '  Blair J',
 '  Kelin',
 '  Francis J',
 '  Mark T',
 '  Michael P',
 '  Patricia A',
 '  Patrick W',
 '  Leonard V',
 '  Vincent G',
 '  Carlos L',
 '  Gerardo',
 '  Deborah M',
 '  Ignacio',
 '  Jaime',
 '  Jesus',
 '  Jorge M',
 '  Jose M',
 '  Joshua E',
 '  Juan C',
 '  Matthew W',
 '  Peter',
 '  Raul A',
 '  Rayna A',
 '  Rene',
 '  Salvador',
 '  Alfredo',
 '  Antonio',
 '  Armando',
 '  Cristina',
 '  Danielle M',
 '  Daylily C',
 '  Deborah A',
 '  Edgar',
 '  Elena',
 '  Genaro',
 '  Hector L',
 '  Hernan L',
 '  Javier',
 '  Jesse',
 '  Jessica',
 '  Jesus',
 '  Jose A',
 '  Jose M',
 '  Joseph M',
 '  David',
 '  Rafael',
 '  Raul',
 '  Juan',
 '  Luis',
 '  Marco',
 '  Marco A',
 '  Margarita',
 '  Maria',
 '  Maria D',
 '  Niki L',
 '  Orlando',
 '  Sherry L',
 '  Ramiro',
 '  Ramon',
 '  Raul',
 '  Richard D',
 '  Robert',
 '  Robin C',
 '  Sally R',
 '  Santiago',
 '  Tibaldo',
 '  Vicente',
 '  Angelina',
 '  Evelyn J',
 '  Charles',
 '  Vidette A',
 '  John F',
 '  Rita N',
 '  Bonita S',
 '  Angel',
 '  Bianca',
 '  Katherine M',
 '  Kenneth',
 '  Tizoc R',
 '  Mark A',
 '  Anthony M',
 '  Dino J',
 '  Michael J',
 '  Chris',
 '  James V',
 '  Steven J',
 '  Neba',
 '  Michael J',
 '  Christophe M',
 '  Kevin J',
 '  Patrick L',
 '  Joseph W',
 '  Mark M',
 '  Bahlebby W',
 '  Anthony J',
 '  Paul S',
 '  Peter R',
 '  Peter R',
 '  Ralph C',
 '  Patrick J',
 '  Mortimer P',
 '  Miguel',
 '  Jade N',
 '  Laura A',
 '  Sonia',
 '  David J',
 '  Teki',
 '  Gregory W',
 '  Michael S',
 '  Alvin A',
 '  Doris C',
 '  Ernesto',
 '  David J',
 '  Michael',
 '  Robert J',
 '  Benedict E',
 '  Chamoon F',
 '  George',
 '  Juan P',
 '  Pedro',
 '  Humberto',
 '  Stephanie',
 '  Federico',
 '  Christopher',
 '  Daniel',
 '  Perry A',
 '  Chris E',
 '  Christopher',
 '  Jeremy C',
 '  Robert J',
 '  Mark A',
 '  Mark E',
 '  Matthew P',
 '  Robert P',
 '  Tami L',
 '  Walter J',
 '  Kevin R',
 '  Albert J',
 '  Alex D',
 '  Andrew J',
 '  Ann-Helen',
 '  Bradley',
 '  Charles E',
 '  Cloutha D',
 '  Corey',
 '  Corey A',
 '  Cory',
 '  Darnetta L',
 '  David C',
 '  David C',
 '  David R',
 '  Deborah L',
 '  Debra L',
 '  Derrick W',
 '  Diana M',
 '  Diane G',
 '  Donald',
 '  Douglas T',
 '  Edward A',
 '  Edward M',
 '  Elizer',
 '  Ellis R',
 '  Eric J',
 '  Eric M',
 '  Gary M',
 '  Glen E',
 '  Hannah L',
 '  Ivy L',
 '  Jacob P',
 '  James E',
 '  James J',
 '  Jerome L',
 '  Jody M',
 '  Joe A',
 '  Joe E',
 '  John S',
 '  John T',
 '  Ernest L',
 '  Roy T',
 '  Kevin B',
 '  Lakisa S',
 '  Lance Q',
 '  Larry D',
 '  Lester J',
 '  Luci A',
 '  Luis F',
 '  Luther',
 '  Luvenia M',
 '  Malinda',
 '  Marion D',
 '  Mark R',
 '  Maurice',
 '  Michael A',
 '  Miguel',
 '  Minnie B',
 '  Oliver',
 '  Paul D',
 '  Paul E',
 '  Paul L',
 '  Quintussia',
 '  Rhonda F',
 '  Rhonda M',
 '  Rhonda M',
 '  Rory A',
 '  Ryan M',
 '  Roslyn',
 '  Roy',
 '  Sally A',
 '  Sharon J',
 '  Stephen R',
 '  Tariq A',
 '  Teddy R',
 '  Teffany',
 '  Theodore C',
 '  Thomas',
 '  Thomas E',
 '  Thomas R',
 '  Todd R',
 '  Tracey A',
 '  Victor O',
 '  Wesley',
 '  Yvette M',
 '  Juanita',
 '  William',
 '  Steve C',
 '  Arturo V',
 '  Daniel',
 '  James N',
 '  Mark',
 '  Pascuala Y',
 '  Gregory A',
 '  Cheryl L',
 '  Adam C',
 '  Anthony J',
 '  Antrinius',
 '  Rhonda C',
 '  Clarence J',
 '  David',
 '  Denise',
 '  Marshall C',
 '  Lisa M',
 '  Martin L',
 '  Michael R',
 '  Rishaunda M',
 '  Sargon A',
 '  Marsha L',
 '  James J',
 '  David L',
 '  Arthur N',
 '  Taras M',
 '  Joseph J',
 '  Daniel',
 '  Katie M',
 '  Phillip A',
 '  Daniel R',
 '  Dean J',
 '  Joseph R',
 '  Kenneth',
 '  Ronaldo C',
 '  Diane E',
 '  Glenn K',
 '  Denise',
 '  John R',
 '  Dean C',
 '  John T',
 '  Samuel',
 '  Rafael',
 '  Michael T',
 '  James E',
 '  Ricardo',
 '  Sara I',
 '  Kevin P',
 '  William J',
 '  Charmain D',
 '  Anthony',
 '  Nick H',
 '  Charles L',
 '  Samuel',
 '  Edward A',
 '  Morgan U',
 '  Theresa C',
 '  Sarah S',
 '  Jamie R',
 '  Michael A',
 '  Nannette',
 '  Benjamin W',
 '  Michelle A',
 '  Brent P',
 '  Frederick',
 '  Gwana R',
 '  Robert K',
 '  Debra L',
 '  Steven C',
 '  Ross A',
 '  Joseph B',
 '  John M',
 '  Frank',
 '  Barry M',
 '  Gino A',
 '  Emmanuel Q',
 '  Christopher J',
 '  Gregory R',
 '  Richard',
 '  Einar N',
 '  Jill L',
 '  Elengical K',
 '  Michael A',
 '  Eric',
 '  Jorge',
 '  Rodrigo A',
 '  Jonathan B',
 '  Jose M',
 '  John F',
 '  Les R',
 '  Irma M',
 '  Wilfredo',
 '  Alain',
 '  Nikos',
 '  Constantin E',
 '  Dimitrios M',
 '  George M',
 '  David L',
 '  Jalissa',
 '  Harinath B',
 '  Prameela K',
 '  Anthony M',
 '  Candelario',
 '  Reynaldo A',
 '  William',
 '  Daniel',
 '  Hiram',
 '  George',
 '  Miguel',
 '  Saul',
 '  Dallas',
 '  David',
 '  Arthur',
 '  Erica',
 '  Rosario',
 '  Alex J',
 '  Barbara L',
 '  John C',
 '  Mario E',
 '  Edwin T',
 '  Adrian T',
 '  Daniella',
 '  Gilbert',
 '  David D',
 '  Lew M',
 '  Joseph',
 '  Edward H',
 '  Christopher J',
 '  Kendra R',
 '  Steven K',
 '  Andrea J',
 '  Iris G',
 '  Raymond',
 '  Rocco',
 '  Mark J',
 '  Xavier',
 '  John',
 '  Marinel',
 '  Kevin B',
 '  Noel',
 '  Darwish A',
 '  Alesia',
 '  Hector A',
 '  Jason',
 '  Miguel A',
 '  Ramon',
 '  Sofia M',
 '  John S',
 '  Ana Luisa',
 '  Frank',
 '  Isabel C',
 '  Jason M',
 '  Shannon M',
 '  Robert J',
 '  Stephanie L',
 '  Daisy',
 '  Jose M',
 '  Michael',
 '  Joan E',
 '  Thomas W',
 '  Constantine J',
 '  Rebecca',
 '  Blanche L',
 '  Fannie',
 '  Vickie',
 '  Vilma S',
 '  Letiscia S',
 '  James',
 '  Nick',
 '  Maryln C',
 '  Yolanda C',
 '  Colette A',
 '  Fatima Z',
 '  Benjamin H',
 '  Roy',
 '  Brian T',
 '  Patrick J',
 '  Helen J',
 '  Anthony M',
 '  Byron',
 '  Chiquita C',
 '  Grace Ann',
 '  Aaron P',
 '  Felicia G',
 '  Travis B',
 '  Clayton E',
 '  David T',
 '  Derrick D',
 '  Jerome',
 '  Louise',
 '  Phillip D',
 '  Sonya',
 '  Donna L',
 '  John V',
 '  Andrea',
 '  Denise C',
 '  Dionne C',
 '  Leatrica M',
 '  Patrick J',
 '  Pearlie',
 '  Roy E',
 '  Robert K',
 '  Robert C',
 '  Paul S',
 '  Thomas J',
 '  Guenther K',
 '  Alberto',
 '  Gary J',
 '  Javier',
 '  Timothy J',
 '  Timothy J',
 '  Rene',
 '  Blas E',
 '  Charles',
 '  Andre J',
 '  Cordia M',
 '  Janet',
 '  Jeremy',
 '  Reginald S',
 '  Oscar F',
 '  Abelardo X',
 '  Cesar',
 '  Christopher J',
 '  Danny',
 '  Esteban',
 '  Francisco',
 '  Francisco',
 '  Nancy',
 '  George',
 '  Hector L',
 ...]

In [132]:
#strip

text = ' I live in Pune '

print(len(text))
print(text)

16
 I live in Pune

In [133]:
print(text.strip())
print(len(text.strip()))

I live in Pune
14

In [51]:
print(text.lstrip())
print(len(text.lstrip()))

I live in Pune
15

In [134]:
print(text.rstrip())
print(len(text.rstrip()))

 I live in Pune
15

In [2]:
# Multilevel indexes

In [33]:
import pandas as pd

In [243]:
chicago = pd.read_csv(R"D:\Data Analyst Classes\Data for Classes\Python\Data Files\chicago.csv")

chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [244]:
chicago = chicago.sort_values(by = 'Employee Annual Salary', ascending = False)

chicago.head()

,Name,Position Title,Department,Employee Annual Salary
23434,"RAPELYEA, SEAN M",ADMINISTRATIVE ASST,MAYOR'S OFFICE,$99996.00
27407,"STARKS, ALVIN D",SERGEANT AT ARMS,CITY COUNCIL,$99936.00
7520,"DUEL, WARD R",FOREMAN OF ELECTRICAL MECHANICS,OEMC,$99840.00
12711,"HOUTSMA, MARK G",COOLING PLANT INSPECTOR,BUILDINGS,$99840.00
4368,"CECOLA, ANTHONY T",FOREMAN OF ELECTRICAL MECHANICS,AVIATION,$99840.00

In [245]:
chicago.set_index(keys = ['Department', 'Name']).head(30)

                                                            Position Title  \
Department       Name
MAYOR'S OFFICE   RAPELYEA,  SEAN M                     ADMINISTRATIVE ASST
CITY COUNCIL     STARKS,  ALVIN D                         SERGEANT AT ARMS
OEMC             DUEL,  WARD R             FOREMAN OF ELECTRICAL MECHANICS
BUILDINGS        HOUTSMA,  MARK G                  COOLING PLANT INSPECTOR
AVIATION         CECOLA,  ANTHONY T        FOREMAN OF ELECTRICAL MECHANICS
WATER MGMNT      LEWSLEY,  ANTHONY B       FOREMAN OF ELECTRICAL MECHANICS
GENERAL SERVICES STEVENS,  RUSSELL C       FOREMAN OF ELECTRICAL MECHANICS
AVIATION         FLAHERTY,  JOHN W         FOREMAN OF ELECTRICAL MECHANICS
TRANSPORTN       HAYES,  JAMES R           FOREMAN OF ELECTRICAL MECHANICS
AVIATION         FRATTO,  MICHAEL T        FOREMAN OF ELECTRICAL MECHANICS
                 RAYBORN,  BILLY           FOREMAN OF ELECTRICAL MECHANICS
BUILDINGS        PULLEN,  TRACY E                  COOLING PLANT INSPECTOR
AVIATION         MC NAMARA,  STEPHEN       FOREMAN OF ELECTRICAL MECHANICS
GENERAL SERVICES MACAULAY,  DONALD W    FRM OF ELECTRICAL MECHANICS (AUTO)
                 OMMUNDSON,  ARNOLD E   FRM OF ELECTRICAL MECHANICS (AUTO)
AVIATION         LYSAUGHT,  JAMES R        FOREMAN OF ELECTRICAL MECHANICS
GENERAL SERVICES DOYLE,  TIMOTHY O         FOREMAN OF ELECTRICAL MECHANICS
                 MC ROY,  MICHAEL J        FOREMAN OF ELECTRICAL MECHANICS
BUILDINGS        TRAVIS,  MESSIAH V                COOLING PLANT INSPECTOR
AVIATION         FOSTER,  KEVIN A          FOREMAN OF ELECTRICAL MECHANICS
                 DONNELLY,  MICHAEL J      FOREMAN OF ELECTRICAL MECHANICS
                 PAYNE,  BILLIE D          FOREMAN OF ELECTRICAL MECHANICS
TRANSPORTN       BOYLE,  DENNIS            FOREMAN OF ELECTRICAL MECHANICS
GENERAL SERVICES DOODY,  JAMES G           FOREMAN OF ELECTRICAL MECHANICS
WATER MGMNT      ZECEVICH,  DRAGAN         FOREMAN OF ELECTRICAL MECHANICS
AVIATION         RYAN,  DANIEL P           FOREMAN OF ELECTRICAL MECHANICS
OEMC             FIGIEL,  JEFFREY J        FOREMAN OF ELECTRICAL MECHANICS
BUILDINGS        ROBINSON,  DANIEL E               COOLING PLANT INSPECTOR
                 GARDNER JR,  RONALD H             COOLING PLANT INSPECTOR
GENERAL SERVICES KEATING,  JOHN R          FOREMAN OF ELECTRICAL MECHANICS

                                       Employee Annual Salary
Department       Name
MAYOR'S OFFICE   RAPELYEA,  SEAN M                  $99996.00
CITY COUNCIL     STARKS,  ALVIN D                   $99936.00
OEMC             DUEL,  WARD R                      $99840.00
BUILDINGS        HOUTSMA,  MARK G                   $99840.00
AVIATION         CECOLA,  ANTHONY T                 $99840.00
WATER MGMNT      LEWSLEY,  ANTHONY B                $99840.00
GENERAL SERVICES STEVENS,  RUSSELL C                $99840.00
AVIATION         FLAHERTY,  JOHN W                  $99840.00
TRANSPORTN       HAYES,  JAMES R                    $99840.00
AVIATION         FRATTO,  MICHAEL T                 $99840.00
                 RAYBORN,  BILLY                    $99840.00
BUILDINGS        PULLEN,  TRACY E                   $99840.00
AVIATION         MC NAMARA,  STEPHEN                $99840.00
GENERAL SERVICES MACAULAY,  DONALD W                $99840.00
                 OMMUNDSON,  ARNOLD E               $99840.00
AVIATION         LYSAUGHT,  JAMES R                 $99840.00
GENERAL SERVICES DOYLE,  TIMOTHY O                  $99840.00
                 MC ROY,  MICHAEL J                 $99840.00
BUILDINGS        TRAVIS,  MESSIAH V                 $99840.00
AVIATION         FOSTER,  KEVIN A                   $99840.00
                 DONNELLY,  MICHAEL J               $99840.00
                 PAYNE,  BILLIE D                   $99840.00
TRANSPORTN       BOYLE,  DENNIS                     $99840.00
GENERAL SERVICES DOODY,  JAMES G                    $99840.00
WATER MGMNT      ZECEVICH,  DRAGAN                  $99840.00
AVIATION         RYAN,  DANIEL P                    $99840.00
OEMC             FIGIEL,  JEFFREY J                 $99840.00
BUILDINGS        ROBINSON,  DANIEL E                $99840.00
                 GARDNER JR,  RONALD H              $99840.00
GENERAL SERVICES KEATING,  JOHN R                   $99840.00

In [246]:
worldstats = pd.read_csv(R"D:\Data Analyst Classes\Data for Classes\Python\Data Files\worldstats.csv")

worldstats.head()

      country  year   Population           GDP
0  Arab World  2015  392022276.0  2.530102e+12
1  Arab World  2014  384222592.0  2.873600e+12
2  Arab World  2013  376504253.0  2.846994e+12
3  Arab World  2012  368802611.0  2.773270e+12
4  Arab World  2011  361031820.0  2.497945e+12

In [247]:
worldstats.set_index(keys = ['country', 'year'])

                  Population           GDP
country    year
Arab World 2015  392022276.0  2.530102e+12
           2014  384222592.0  2.873600e+12
           2013  376504253.0  2.846994e+12
           2012  368802611.0  2.773270e+12
           2011  361031820.0  2.497945e+12
...                      ...           ...
Zimbabwe   1964    4279561.0  1.217138e+09
           1963    4140804.0  1.159512e+09
           1962    4006262.0  1.117602e+09
           1961    3876638.0  1.096647e+09
           1960    3752390.0  1.052990e+09

[11211 rows x 2 columns]

In [248]:
worldstats.set_index(keys = ['year', 'country'])

                  Population           GDP
year country
2015 Arab World  392022276.0  2.530102e+12
2014 Arab World  384222592.0  2.873600e+12
2013 Arab World  376504253.0  2.846994e+12
2012 Arab World  368802611.0  2.773270e+12
2011 Arab World  361031820.0  2.497945e+12
...                      ...           ...
1964 Zimbabwe      4279561.0  1.217138e+09
1963 Zimbabwe      4140804.0  1.159512e+09
1962 Zimbabwe      4006262.0  1.117602e+09
1961 Zimbabwe      3876638.0  1.096647e+09
1960 Zimbabwe      3752390.0  1.052990e+09

[11211 rows x 2 columns]

In [249]:
# country is not in index currently

worldstats.country.value_counts()

country
Hong Kong SAR, China      56
Greece                    56
Guyana                    56
Honduras                  56
Caribbean small states    56
                          ..
Channel Islands           10
South Sudan                8
Myanmar                    4
Somalia                    3
Cayman Islands             2
Name: count, Length: 252, dtype: int64

In [250]:
unique_countries = worldstats['country'].unique()



num_unique_countries = len(unique_countries)

num_unique_countries

252

In [251]:
unique_countries

array(['Arab World', 'Caribbean small states',
       'Central Europe and the Baltics', 'Early-demographic dividend',
       'East Asia & Pacific',
       'East Asia & Pacific (excluding high income)',
       'East Asia & Pacific (IDA & IBRD countries)', 'Euro area',
       'Europe & Central Asia',
       'Europe & Central Asia (excluding high income)',
       'Europe & Central Asia (IDA & IBRD countries)', 'European Union',
       'Fragile and conflict affected situations',
       'Heavily indebted poor countries (HIPC)', 'High income',
       'IBRD only', 'IDA & IBRD total', 'IDA blend', 'IDA only',
       'IDA total', 'Late-demographic dividend',
       'Latin America & Caribbean',
       'Latin America & Caribbean (excluding high income)',
       'Latin America & the Caribbean (IDA & IBRD countries)',
       'Least developed countries: UN classification',
       'Low & middle income', 'Low income', 'Lower middle income',
       'Middle East & North Africa',
       'Middle East & North Africa (excluding high income)',
       'Middle East & North Africa (IDA & IBRD countries)',
       'Middle income', 'North America', 'OECD members',
       'Other small states', 'Pacific island small states',
       'Post-demographic dividend', 'Pre-demographic dividend',
       'Small states', 'South Asia', 'South Asia (IDA & IBRD)',
       'Sub-Saharan Africa', 'Sub-Saharan Africa (excluding high income)',
       'Sub-Saharan Africa (IDA & IBRD countries)', 'Upper middle income',
       'World', 'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Cayman Islands', 'Central African Republic', 'Chad',
       'Channel Islands', 'Chile', 'China', 'Colombia', 'Comoros',
       'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador',
       'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Ethiopia', 'Faroe Islands', 'Fiji', 'Finland',
       'France', 'French Polynesia', 'Gabon', 'Gambia, The', 'Georgia',
       'Germany', 'Ghana', 'Greece', 'Greenland', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Isle of Man', 'Israel',
       'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya',
       'Kiribati', 'Korea, Rep.', 'Kosovo', 'Kuwait', 'Kyrgyz Republic',
       'Lao PDR', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao SAR, China',
       'Macedonia, FYR', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius',
       'Mexico', 'Micronesia, Fed. Sts.', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan',
       'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovak Republic',
       'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa',
       'South Sudan', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis',
       'St. Lucia', 'St. Vincent and the Grenadines', 'Sudan', 'Suriname',
       'Swaziland', 'Sweden', 'Switzerland', 'Syrian Arab Republic',
       'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo',
       'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Vietnam',
       'Virgin Islands (U.S.)', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [252]:
my_list = worldstats['country'].tolist()

my_list

['Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Arab World',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Caribbean small states',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Central Europe and the Baltics',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'Early-demographic dividend',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (excluding high income)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (IDA & IBRD countries)',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Euro area',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (excluding high income)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (IDA & IBRD countries)',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'European Union',
 'Fragile and conflict affected situations',
 'Fragile and conflict affected situations',
 'Fragile and conflict affected situations',
 'Fragile and conflict affected situations',
 'Fragile and conflict affected situations',
 'Fragile and conflict affected situations',
 'Fragile and conflict affected situations',
 'Fragile and conflict affected situations',
 'Fragile and conflict affected situations',
 'Fragile and conflict affected situations',
 'Fragile and conflict affected situations',
 'Fragile and conflict affected situations',
 'Fragile and conflict affected situations',
 'Fragile and conflict affected situations',
 'Fragile and conflict affected situations',
 'Fragile and conflict affected situations',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',
 'Heavily indebted poor countries (HIPC)',

In [10]:
unique_values = set(my_list)

unique_values

{'Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Arab World',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas, The',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Caribbean small states',
 'Cayman Islands',
 'Central African Republic',
 'Central Europe and the Baltics',
 'Chad',
 'Channel Islands',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo, Dem. Rep.',
 'Congo, Rep.',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Early-demographic dividend',
 'East Asia & Pacific',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (excluding high income)',
 'Ecuador',
 'Egypt, Arab Rep.',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Euro area',
 'Europe & Central Asia',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (excluding high income)',
 'European Union',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'Fragile and conflict affected situations',
 'France',
 'French Polynesia',
 'Gabon',
 'Gambia, The',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Greenland',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Heavily indebted poor countries (HIPC)',
 'High income',
 'Honduras',
 'Hong Kong SAR, China',
 'Hungary',
 'IBRD only',
 'IDA & IBRD total',
 'IDA blend',
 'IDA only',
 'IDA total',
 'Iceland',
 'India',
 'Indonesia',
 'Iran, Islamic Rep.',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Korea, Rep.',
 'Kosovo',
 'Kuwait',
 'Kyrgyz Republic',
 'Lao PDR',
 'Late-demographic dividend',
 'Latin America & Caribbean',
 'Latin America & Caribbean (excluding high income)',
 'Latin America & the Caribbean (IDA & IBRD countries)',
 'Latvia',
 'Least developed countries: UN classification',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Low & middle income',
 'Low income',
 'Lower middle income',
 'Luxembourg',
 'Macao SAR, China',
 'Macedonia, FYR',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia, Fed. Sts.',
 'Middle East & North Africa',
 'Middle East & North Africa (IDA & IBRD countries)',
 'Middle East & North Africa (excluding high income)',
 'Middle income',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North America',
 'Norway',
 'OECD members',
 'Oman',
 'Other small states',
 'Pacific island small states',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Post-demographic dividend',
 'Pre-demographic dividend',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovak Republic',
 'Slovenia',
 'Small states',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Asia',
 'South Asia (IDA & IBRD)',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'St. Kitts and Nevis',
 'St. Lucia',
 'St. Vincent and the Grenadines',
 'Sub-Saharan Africa',
 'Sub-Saharan Africa (IDA & IBRD countries)',
 'Sub-Saharan Africa (excluding high income)',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Upper middle income',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela, RB',
 'Vietnam',
 'Virgin Islands (U.S.)',
 'West Bank and Gaza',
 'World',
 'Yemen, Rep.',
 'Zambia',
 'Zimbabwe'}

In [11]:
len(unique_values)

252

In [253]:
worldstats = pd.read_csv(R"D:\Data Analyst Classes\Data for Classes\Python\Data Files\worldstats.csv", index_col= ['country','year'])

worldstats.head()

                  Population           GDP
country    year
Arab World 2015  392022276.0  2.530102e+12
           2014  384222592.0  2.873600e+12
           2013  376504253.0  2.846994e+12
           2012  368802611.0  2.773270e+12
           2011  361031820.0  2.497945e+12

In [254]:
worldstats.loc[('Arab World', 2005)]['GDP']

1184734704133.27

In [14]:
worldstats.index

MultiIndex(levels=[['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Arab World', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Caribbean small states', 'Cayman Islands', 'Central African Republic', 'Central Europe and the Baltics', 'Chad', 'Channel Islands', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', 'Cote d'Ivoire', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Early-demographic dividend', 'East Asia & Pacific', 'East Asia & Pacific (IDA & IBRD countries)', 'East Asia & Pacific (excluding high income)', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Euro area', 'Europe & Central Asia', 'Europe & Central Asia (IDA & IBRD countries)', 'Europe & Central Asia (excluding high income)', 'European Union', 'Faroe Islands', 'Fiji', 'Finland', 'Fragile and conflict affected situations', 'France', 'French Polynesia', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Greenland', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heavily indebted poor countries (HIPC)', 'High income', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'IBRD only', 'IDA & IBRD total', 'IDA blend', 'IDA only', 'IDA total', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Korea, Rep.', 'Kosovo', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Late-demographic dividend', 'Latin America & Caribbean', 'Latin America & Caribbean (excluding high income)', 'Latin America & the Caribbean (IDA & IBRD countries)', 'Latvia', 'Least developed countries: UN classification', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Low & middle income', 'Low income', 'Lower middle income', 'Luxembourg', 'Macao SAR, China', 'Macedonia, FYR', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.', 'Middle East & North Africa', 'Middle East & North Africa (IDA & IBRD countries)', 'Middle East & North Africa (excluding high income)', 'Middle income', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North America', 'Norway', 'OECD members', 'Oman', 'Other small states', 'Pacific island small states', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Post-demographic dividend', 'Pre-demographic dividend', 'Puerto Rico', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia', 'Small states', 'Solomon Islands', 'Somalia', 'South Africa', 'South Asia', 'South Asia (IDA & IBRD)', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia', 'St. Vincent and the Grenadines', 'Sub-Saharan Africa', 'Sub-Saharan Africa (IDA & IBRD countries)', 'Sub-Saharan Africa (excluding high income)', 'Sudan', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Upper middle income', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Vietnam', 'Virgin Islands (U.S.)', 'West Bank and Gaza', 'World', 'Yemen, Rep.', 'Zambia', 'Zimbabwe'], [1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015]],

In [146]:
worldstats.index.get_level_values(0).unique()

Index(['Arab World', 'Caribbean small states',
       'Central Europe and the Baltics', 'Early-demographic dividend',
       'East Asia & Pacific', 'East Asia & Pacific (excluding high income)',
       'East Asia & Pacific (IDA & IBRD countries)', 'Euro area',
       'Europe & Central Asia',
       'Europe & Central Asia (excluding high income)',
       ...
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Vietnam',
       'Virgin Islands (U.S.)', 'West Bank and Gaza', 'Yemen, Rep.', 'Zambia',
       'Zimbabwe'],
      dtype='object', name='country', length=252)

In [151]:
worldstats.index.rename(names = ['Desh','Saal'],inplace = True)

In [152]:
worldstats.head()

                  Population           GDP
Desh       Saal
Arab World 2015  392022276.0  2.530102e+12
           2014  384222592.0  2.873600e+12
           2013  376504253.0  2.846994e+12
           2012  368802611.0  2.773270e+12
           2011  361031820.0  2.497945e+12

In [255]:
wdst = worldstats.rename(index={'Desh': 'country', 'Saal': 'year'})

In [256]:
wdst.head()

                  Population           GDP
country    year
Arab World 2015  392022276.0  2.530102e+12
           2014  384222592.0  2.873600e+12
           2013  376504253.0  2.846994e+12
           2012  368802611.0  2.773270e+12
           2011  361031820.0  2.497945e+12

In [257]:
worldstats.index.rename(names = ['Country','Year'],inplace = True)

worldstats.head()

                  Population           GDP
Country    Year
Arab World 2015  392022276.0  2.530102e+12
           2014  384222592.0  2.873600e+12
           2013  376504253.0  2.846994e+12
           2012  368802611.0  2.773270e+12
           2011  361031820.0  2.497945e+12

In [259]:
worldstats.swaplevel('Country','Year').head()

                  Population           GDP
Year Country
2015 Arab World  392022276.0  2.530102e+12
2014 Arab World  384222592.0  2.873600e+12
2013 Arab World  376504253.0  2.846994e+12
2012 Arab World  368802611.0  2.773270e+12
2011 Arab World  361031820.0  2.497945e+12

In [260]:
worldstats.head()

                  Population           GDP
Country    Year
Arab World 2015  392022276.0  2.530102e+12
           2014  384222592.0  2.873600e+12
           2013  376504253.0  2.846994e+12
           2012  368802611.0  2.773270e+12
           2011  361031820.0  2.497945e+12

In [261]:
wdst = worldstats.swaplevel()

wdst.head()

                  Population           GDP
Year Country
2015 Arab World  392022276.0  2.530102e+12
2014 Arab World  384222592.0  2.873600e+12
2013 Arab World  376504253.0  2.846994e+12
2012 Arab World  368802611.0  2.773270e+12
2011 Arab World  361031820.0  2.497945e+12

In [262]:
wdst = worldstats.swaplevel(i = 0, j = -2)

wdst.head()

                  Population           GDP
Country    Year
Arab World 2015  392022276.0  2.530102e+12
           2014  384222592.0  2.873600e+12
           2013  376504253.0  2.846994e+12
           2012  368802611.0  2.773270e+12
           2011  361031820.0  2.497945e+12

In [263]:
wdst = worldstats.swaplevel(i = 1, j = 0)

wdst.head()

                  Population           GDP
Year Country
2015 Arab World  392022276.0  2.530102e+12
2014 Arab World  384222592.0  2.873600e+12
2013 Arab World  376504253.0  2.846994e+12
2012 Arab World  368802611.0  2.773270e+12
2011 Arab World  361031820.0  2.497945e+12

In [161]:
import pandas as pd

In [264]:
worldstats = pd.read_csv(R"D:\Data Analyst Classes\Data for Classes\Python\Data Files\worldstats.csv")

worldstats.head()

      country  year   Population           GDP
0  Arab World  2015  392022276.0  2.530102e+12
1  Arab World  2014  384222592.0  2.873600e+12
2  Arab World  2013  376504253.0  2.846994e+12
3  Arab World  2012  368802611.0  2.773270e+12
4  Arab World  2011  361031820.0  2.497945e+12

In [265]:
worldstats.set_index(['country','year'], inplace = True)

In [266]:
worldstats.head()

                  Population           GDP
country    year
Arab World 2015  392022276.0  2.530102e+12
           2014  384222592.0  2.873600e+12
           2013  376504253.0  2.846994e+12
           2012  368802611.0  2.773270e+12
           2011  361031820.0  2.497945e+12

In [267]:
# stack -  converts columns into rows

st_df = worldstats.stack()

st_df

country     year
Arab World  2015  Population    3.920223e+08
                  GDP           2.530102e+12
            2014  Population    3.842226e+08
                  GDP           2.873600e+12
            2013  Population    3.765043e+08
                                    ...
Zimbabwe    1962  GDP           1.117602e+09
            1961  Population    3.876638e+06
                  GDP           1.096647e+09
            1960  Population    3.752390e+06
                  GDP           1.052990e+09
Length: 22422, dtype: float64

In [268]:
st_df = st_df.to_frame()

st_df.head()

                                       0
country    year
Arab World 2015 Population  3.920223e+08
                GDP         2.530102e+12
           2014 Population  3.842226e+08
                GDP         2.873600e+12
           2013 Population  3.765043e+08

In [269]:
st_df.rename(columns = {0: 'Data'} , inplace = True)

st_df.head()

                                    Data
country    year
Arab World 2015 Population  3.920223e+08
                GDP         2.530102e+12
           2014 Population  3.842226e+08
                GDP         2.873600e+12
           2013 Population  3.765043e+08

In [270]:
unst_df = st_df.unstack()

unst_df.head()

                       Data
                 Population           GDP
country     year
Afghanistan 1960  8994793.0  5.377778e+08
            1961  9164945.0  5.488889e+08
            1962  9343772.0  5.466667e+08
            1963  9531555.0  7.511112e+08
            1964  9728645.0  8.000000e+08

In [271]:
unst_df.columns.levels

FrozenList([['Data'], ['Population', 'GDP']])

In [169]:
unst_df.index.levels

FrozenList([['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Arab World', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Caribbean small states', 'Cayman Islands', 'Central African Republic', 'Central Europe and the Baltics', 'Chad', 'Channel Islands', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', 'Cote d'Ivoire', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Early-demographic dividend', 'East Asia & Pacific', 'East Asia & Pacific (IDA & IBRD countries)', 'East Asia & Pacific (excluding high income)', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Euro area', 'Europe & Central Asia', 'Europe & Central Asia (IDA & IBRD countries)', 'Europe & Central Asia (excluding high income)', 'European Union', 'Faroe Islands', 'Fiji', 'Finland', 'Fragile and conflict affected situations', 'France', 'French Polynesia', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Greenland', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heavily indebted poor countries (HIPC)', 'High income', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'IBRD only', 'IDA & IBRD total', 'IDA blend', ...], [1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015]])

In [272]:
unst_df.columns = [col[1] for col in unst_df.columns]

unst_df

                  Population           GDP
country     year
Afghanistan 1960   8994793.0  5.377778e+08
            1961   9164945.0  5.488889e+08
            1962   9343772.0  5.466667e+08
            1963   9531555.0  7.511112e+08
            1964   9728645.0  8.000000e+08
...                      ...           ...
Zimbabwe    2011  14255592.0  1.095623e+10
            2012  14565482.0  1.239272e+10
            2013  14898092.0  1.349023e+10
            2014  15245855.0  1.419691e+10
            2015  15602751.0  1.389294e+10

[11211 rows x 2 columns]

In [171]:
temp_list =[]
for col in unst_df.columns:
    temp_list.append(col[1])
print(temp_list)


unst_df.columns = temp_list

unst_df.head()

['o', 'D']

                          o             D
country     year
Afghanistan 1960  8994793.0  5.377778e+08
            1961  9164945.0  5.488889e+08
            1962  9343772.0  5.466667e+08
            1963  9531555.0  7.511112e+08
            1964  9728645.0  8.000000e+08

In [172]:
unst_df.rename(columns = {'o': 'Population', 'D':'GDP'} , inplace = True)

unst_df.head()

                  Population           GDP
country     year
Afghanistan 1960   8994793.0  5.377778e+08
            1961   9164945.0  5.488889e+08
            1962   9343772.0  5.466667e+08
            1963   9531555.0  7.511112e+08
            1964   9728645.0  8.000000e+08

In [273]:
salesman = pd.read_csv(R"D:\Data Analyst Classes\Data for Classes\Python\Data Files\salesmen.csv")

salesman.head()

     Date Salesman  Revenue
0  1/1/16      Bob     7172
1  1/2/16      Bob     6362
2  1/3/16      Bob     5982
3  1/4/16      Bob     7917
4  1/5/16      Bob     7837

In [274]:
salesman.Salesman.value_counts()

Salesman
Bob       366
Ronald    366
Dave      366
Jeb       366
Oscar     366
Name: count, dtype: int64

In [275]:
salesman.pivot(index= 'Date', columns = 'Salesman', values = 'Revenue')

Salesman   Bob  Dave   Jeb  Oscar  Ronald
Date
1/1/16    7172  1864  4430   5250    2639
1/10/16   7543  7105   301   7663    8267
1/11/16   1053  6851  9489   8888    1340
1/12/16   4362  7147  8719   3092     279
1/13/16   6812  6160  2349   6139    7540
...        ...   ...   ...    ...     ...
9/5/16     992   211  2439   7743    4252
9/6/16     556  7293  7585   5072    1112
9/7/16    6499  9774  6669   5230    3608
9/8/16    9621  8194  3058   7755    5762
9/9/16    1231  4733  6823   5684    8922

[366 rows x 5 columns]

In [276]:
salesman.pivot_table(values = 'Revenue', index ='Salesman', aggfunc = 'mean' )

              Revenue
Salesman
Bob       4992.292350
Dave      5079.407104
Jeb       5241.579235
Oscar     4857.319672
Ronald    4992.109290

In [277]:
salesman.pivot_table(values = 'Revenue', index ='Salesman', aggfunc = 'max' )

          Revenue
Salesman
Bob          9999
Dave         9939
Jeb          9939
Oscar        9971
Ronald       9991

In [278]:
salesman.pivot_table(values = 'Revenue', index ='Salesman', aggfunc = 'std' )

              Revenue
Salesman
Bob       2883.870220
Dave      2831.619027
Jeb       2838.461727
Oscar     2843.760302
Ronald    2877.214155